"""First real articulated range-plus-Q1-orientation batch smoother.

The only per-knot translational state is the pelvis/root position. Every other
sensor position is generated by fixed-length articulated chains whose edge
directions are driven by interpolated Q1 orientation evidence.
"""
from __future__ import annotations
from dataclasses import dataclass
import time
import numpy as np
from scipy.optimize import least_squares
from scipy.sparse import lil_matrix
from scipy.spatial.transform import Rotation, Slerp
from .robust import PairHealth

NODES=("BSFC2CC","BSF31CC","BSFAA61","BSFB165","BSF1120","BSFEC35","BSF44AD","BSF6C53","BSF3C79","BSF8BC4")
PARENT={"BSF31CC":"BSFC2CC","BSFAA61":"BSF31CC","BSFB165":"BSFAA61","BSF1120":"BSF31CC","BSFEC35":"BSF1120","BSF44AD":"BSFC2CC","BSF6C53":"BSF44AD","BSF3C79":"BSFC2CC","BSF8BC4":"BSF3C79"}

def q_wxyz_to_rotation(q): return Rotation.from_quat(np.asarray(q)[..., [1,2,3,0]])

@dataclass
class SliceData:
 name:str; start_ns:int; stop_ns:int; q1:dict; ranges:np.ndarray; t4:dict

def interp_rot(times,quats,query):
 order=np.argsort(times); times=np.asarray(times)[order]; quats=np.asarray(quats)[order]
 keep=np.r_[True,np.diff(times)>0]; times=times[keep]; quats=quats[keep]
 query=np.clip(query,times[0],times[-1]); return Slerp(times,q_wxyz_to_rotation(quats))(query)

class ArticulatedMotion:
 def __init__(self,static_positions,static_q):
  self.static_positions={k:np.asarray(v,float) for k,v in static_positions.items()}; self.static_q=static_q
  self.edge={n:self.static_positions[n]-self.static_positions[p] for n,p in PARENT.items()}
  self.lengths={n:float(np.linalg.norm(v)) for n,v in self.edge.items()}
 def relative_positions(self,data,times):
  times=np.asarray(times,np.int64); out={"BSFC2CC":np.zeros((len(times),3))}
  rotations={}
  for n in NODES:
   q=data.q1[n]; r=interp_rot(q["time_ns"],q["q_wxyz"],times)
   rotations[n]=r*self.static_q[n].inv()
  for n in NODES[1:]:
   p=PARENT[n]; edge=rotations[n].apply(np.repeat(self.edge[n][None,:],len(times),axis=0))
   out[n]=out[p]+edge
  return out

def interpolate_root(knots_ns,root,query_ns):
 q=np.asarray(query_ns); idx=np.searchsorted(knots_ns,q,side="right")-1; idx=np.clip(idx,0,len(knots_ns)-2)
 u=((q-knots_ns[idx])/(knots_ns[idx+1]-knots_ns[idx])).reshape(-1,1)
 return (1-u)*root[idx]+u*root[idx+1],idx,u[:,0]

def range_prediction(knots_ns,root,ranges,relative):
 rt,_,_=interpolate_root(knots_ns,root,ranges["time_ns"])
 pos=rt+np.vstack([relative[n][i] for i,n in enumerate(ranges["node"])])
 return np.linalg.norm(pos-ranges["anchor_xyz"],axis=1),pos

def solve(data,motion,pair_sigma,knot_ms=100.0,drop_anchor=None,drop_node=None,drop_interval=None,range_bias=None,time_shift_ns=0,initial_offset=(0,0,0)):
 ranges=data.ranges.copy(); mask=np.ones(len(ranges),bool)
 if drop_anchor is not None: mask&=ranges["anchor"]!=drop_anchor
 if drop_node is not None: mask&=ranges["node"]!=drop_node
 if drop_interval is not None:
  start,stop=drop_interval; mask&=~((ranges["time_ns"]>=start)&(ranges["time_ns"]<=stop))
 ranges=ranges[mask]; ranges["time_ns"]+=int(time_shift_ns)
 if range_bias is not None:
  node,anchor,start,stop,bias=range_bias; hit=(ranges["node"]==node)&(ranges["anchor"]==anchor)&(ranges["time_ns"]>=start)&(ranges["time_ns"]<=stop); ranges["range_m"][hit]+=bias
 knots=np.arange(data.start_ns,data.stop_ns+int(knot_ms*1e6),int(knot_ms*1e6),dtype=np.int64)
 if knots[-1]<data.stop_ns: knots=np.r_[knots,data.stop_ns]
 pelvis=data.t4["BSFC2CC"]; x0=np.empty((len(knots),3))
 for j in range(3): x0[:,j]=np.interp(knots,pelvis["time_ns"],pelvis["position_m"][:,j])
 x0 += np.asarray(initial_offset,float)
 rel=motion.relative_positions(data,ranges["time_ns"])
 sigma=np.array([pair_sigma[(n,int(a))] for n,a in zip(ranges["node"],ranges["anchor"])])
 pred0,_=range_prediction(knots,x0,ranges,rel); health={k:PairHealth() for k in pair_sigma}
 conf=np.ones(len(ranges))
 for i,(n,a,innov) in enumerate(zip(ranges["node"],ranges["anchor"],(pred0-ranges["range_m"])/sigma)):
  conf[i]=health[(n,int(a))].update(float(innov))
 def fun(flat):
  root=flat.reshape(-1,3); pred,_=range_prediction(knots,root,ranges,rel)
  rr=np.sqrt(conf)*(pred-ranges["range_m"])/sigma
  accel=(root[2:]-2*root[1:-1]+root[:-2])/0.04
  velocity=(root[1:]-root[:-1])/0.40
  return np.r_[rr,accel.ravel(),velocity.ravel()]
 n=len(knots); m=len(ranges)+3*max(0,n-2)+3*(n-1); sp=lil_matrix((m,3*n),dtype=int)
 _,idx,_=interpolate_root(knots,x0,ranges["time_ns"])
 for row,k in enumerate(idx): sp[row,3*k:3*k+6]=1
 row=len(ranges)
 for k in range(n-2): sp[row+3*k:row+3*k+3,3*k:3*k+9]=1
 row+=3*max(0,n-2)
 for k in range(n-1): sp[row+3*k:row+3*k+3,3*k:3*k+6]=1
 started=time.time(); result=least_squares(fun,x0.ravel(),jac_sparsity=sp.tocsr(),loss="cauchy",f_scale=2.5,max_nfev=160,ftol=1e-5,xtol=1e-5,gtol=1e-5,verbose=0)
 root=result.x.reshape(-1,3); pred,pos=range_prediction(knots,root,ranges,rel); residual=pred-ranges["range_m"]
 return {"result":result,"runtime_s":time.time()-started,"knots_ns":knots,"root":root,"ranges":ranges,"prediction":pred,"positions_at_ranges":pos,"residual":residual,"sigma":sigma,"confidence":conf,"motion":motion}
