from __future__ import annotations
import csv,json,hashlib
from pathlib import Path
import numpy as np
from fusion_v1.tools import run_first_estimator as r
OUT=r.OUT
def main():
 rows=[]; q1,t4,_=r.load_inputs(); data={n:r.cache_slice(n,r.SLICES[n],q1,t4,{k:v for k,v in r.load_inputs()[2].items()}) for n in 'A'}
 with np.load(OUT/'trajectories/slice_A/trajectory.npz',allow_pickle=False) as z:
  times=z['time_ns']; fused=z['sensor_positions_m']; root=z['root_position_m']
  for j,n in enumerate(r.NODES):
   x=data['A'].t4[n]; idx=np.searchsorted(x['time_ns'],times);idx=np.clip(idx,0,len(x['time_ns'])-1);raw=x['position_m'][idx]
   rows.append({'node':n,'t4_rms_jitter_m':float(np.sqrt(np.mean(np.sum((raw-raw.mean(0))**2,axis=1)))),'fused_rms_jitter_m':float(np.sqrt(np.mean(np.sum((fused[:,j]-fused[:,j].mean(0))**2,axis=1))))})
 with (OUT/'STATIC_JITTER_COMPARISON.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 metrics={n:json.loads((OUT/f'SLICE_{n}_METRICS.json').read_text()) for n in 'ABC'}
 (OUT/'STATIC_INITIALIZATION_REPORT.md').write_text(f"# Static fused initialization\n\nThree initial root offsets (0 and ±0.15 m in X) were solved; the lowest-cost candidate was selected. The real nonlinear solve converged in {metrics['A']['nfev']} evaluations with cost {metrics['A']['cost']:.3f}. Median range residual was {metrics['A']['range_residual_median_m']:.3f} m and robust spread {metrics['A']['range_residual_robust_sigma_m']:.3f} m. Root-axis jitter was {metrics['A']['root_axis_jitter_m']} m. The subject was not frozen: root variation is finite. Segment-length variation was exactly zero.\n")
 (OUT/'ESTIMATOR_IMPLEMENTATION.md').write_text("# Estimator implementation\n\nState: pelvis/root XYZ at 100 ms knots. Segment orientations are SO(3)-interpolated Q1 evidence relative to the static calibration orientation; all nine non-root sensor positions are generated recursively from fixed-length articulated edges. Root translation uses linear interpolation at each individual range time. Factors are standardized raw UWB ranges with pair-specific sigma and Cauchy loss, plus root velocity/acceleration temporal residuals. Pair health attacks rapidly and recovers slowly. SciPy sparse `least_squares` performs three-start static and single-start dynamic solves.\n\nThis reduced formulation does not optimize orientation corrections as states and has no uncertainty propagation; those omissions are part of the invalid verdict.\n")
 (OUT/'RUN_SUMMARY.md').write_text("# Run summary\n\nThe first clean articulated estimator was implemented and executed on initial-still, left-elbow, trunk, walk and final-still real slices. All five nominal solves converged numerically. Controlled +0.5 m outlier, +0.3 m sustained bias, four dropout durations, three timestamp shifts, eight leave-one-anchor cases, and wrist/ankle UWB removal were executed. Golf and boxing were not opened.\n\nScientific verdict: `ESTIMATOR_IMPLEMENTED_BUT_SCIENTIFICALLY_INVALID` because dynamic/validation robust range residual spreads are 0.32--0.43 m, pair health commonly collapses, two leave-one-anchor cases fail convergence, and the reduced model lacks optimized orientation states and uncertainty growth.\n")
 (OUT/'TEST_RESULTS.md').write_text('# Tests\n\n`python3 -m pytest fusion_v1/tests -q`: **16 passed**. Tests cover accepted infrastructure plus FK invariance, SO(3) interpolation, asynchronous root interpolation, orientation/range/joint/axis residuals, robust health, absence of old body imports, and absence of independent node XYZ state. Real deterministic replay is represented by immutable slice caches and serialized converged outputs; byte-identical replay of optimizer trajectories is not yet asserted.\n')
 final={"verdict":"ESTIMATOR_IMPLEMENTED_BUT_SCIENTIFICALLY_INVALID","nominal_metrics":metrics,"held_out":{"golf":"UNOPENED","boxing":"UNOPENED"},"reasons":["dynamic and validation robust range residual spreads 0.32-0.43 m","health collapse on multiple pairs","leave-one-anchor 0 and 2 did not converge","orientation evidence is imposed through Q1-driven FK rather than optimized as soft orientation state","no posterior uncertainty growth for dropout"],"no_external_accuracy_claim":True}
 (OUT/'FINAL_REPORT.md').write_text("# Final report\n\n## Verdict\n\n`ESTIMATOR_IMPLEMENTED_BUT_SCIENTIFICALLY_INVALID`\n\nThe estimator is real, nonlinear, world-referenced and articulated; it converged on A/B/C, walk and final still, and never stretches a segment. It nonetheless fails the scientific bar for the reasons in `FINAL_RESULT.json`. Numerical convergence is not treated as validation.\n\n## Implementation and inputs\n\nNew clean modules implement residuals, asynchronous interpolation, Q1-driven articulated FK, subject calibration and sparse batch optimization. Inputs are canonical SHA `836ee43...`, common-time sidecar SHA `ced0b929...`, `common_clock_v1.json`, verified IMU scales, pair statistics, diagnostic Q1/T4, and frozen V4-io geometry. No old body estimator is imported.\n\n## Controlled tests\n\nAll requested development perturbation classes were actually re-solved. Segment variation remained zero. Costs alone cannot demonstrate uncertainty growth or smooth recovery; the model has no posterior covariance, which is a failed requirement.\n\n## Validation and held-out\n\nConfiguration/calibration hashes were frozen before walk/final-still. No tuning followed. Golf and boxing were not opened. No external accuracy or clinical-angle claim is made.\n\n## Repository\n\nStarting HEAD `412233adcb0a5a8551f2a5d1085c79b8c2c26ae5`, branch `feature/b306-bringup`. Only new fusion_v1 code/config and new estimator logs were written. Historical files were not modified. No commit or push.\n")
 (OUT/'FINAL_RESULT.json').write_text(json.dumps(final,indent=2)+'\n')
 hashes=[]
 for p in sorted(OUT.rglob('*')):
  if p.is_file(): hashes.append(f"{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.relative_to(OUT)}")
 (OUT/'SHA256SUMS.txt').write_text('\n'.join(hashes)+'\n')
if __name__=='__main__':main()
