"""Calibration-only articulated batch model and numerical observability audit.

The model uses one shared body.  UWB observations are antenna positions; the
placement-node lines are never treated as bones.  Segment origins and virtual
joint centres are generated by forward kinematics from immutable static
geometry, while Q1 sensor attitudes are mapped through fitted session
sensor-to-segment extrinsics.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Mapping

import numpy as np
from scipy.optimize import least_squares
from scipy.spatial.transform import Rotation


SEGMENTS = (
    "Pelvis", "Torso", "UpperArm_L", "Forearm_L", "UpperArm_R", "Forearm_R",
    "Thigh_L", "Shank_L", "Thigh_R", "Shank_R",
)
SEGMENT_INDEX = {name: index for index, name in enumerate(SEGMENTS)}
GEOMETRY_NAMES = (
    "torso_separation_m", "shoulder_half_width_m", "shoulder_height_m",
    "hip_half_width_m", "hip_vertical_m", "upper_arm_L_m", "forearm_L_m",
    "upper_arm_R_m", "forearm_R_m", "thigh_L_m", "shank_L_m",
    "thigh_R_m", "shank_R_m",
)
HINGES = (
    ("UpperArm_L", "Forearm_L", "elbow_L"),
    ("UpperArm_R", "Forearm_R", "elbow_R"),
    ("Thigh_L", "Shank_L", "knee_L"),
    ("Thigh_R", "Shank_R", "knee_R"),
)


@dataclass(frozen=True)
class CalibrationSamples:
    time_ns: np.ndarray
    action: np.ndarray
    position_v4_m: np.ndarray
    covariance_v4_m2: np.ndarray
    orientation_N_from_B: np.ndarray
    valid_position: np.ndarray

    def __post_init__(self) -> None:
        count = len(self.time_ns)
        if self.position_v4_m.shape != (count, len(SEGMENTS), 3):
            raise ValueError("position sample shape mismatch")
        if self.orientation_N_from_B.shape != (count, len(SEGMENTS), 3, 3):
            raise ValueError("orientation sample shape mismatch")


@dataclass(frozen=True)
class Geometry:
    torso_separation_m: float
    shoulder_half_width_m: float
    shoulder_height_m: float
    hip_half_width_m: float
    hip_vertical_m: float
    upper_arm_L_m: float
    forearm_L_m: float
    upper_arm_R_m: float
    forearm_R_m: float
    thigh_L_m: float
    shank_L_m: float
    thigh_R_m: float
    shank_R_m: float

    def vector(self) -> np.ndarray:
        return np.asarray([getattr(self, name) for name in GEOMETRY_NAMES], float)


@dataclass(frozen=True)
class CalibrationCandidate:
    R_N_from_V4: np.ndarray
    R_segment_from_sensor: Mapping[str, np.ndarray]
    geometry: Geometry
    cost: float
    optimality: float
    iterations: int
    success: bool
    message: str


def _proper(rotation_vector: np.ndarray) -> np.ndarray:
    matrix = Rotation.from_rotvec(np.asarray(rotation_vector, float)).as_matrix()
    if np.linalg.det(matrix) < 0.999999:
        raise ValueError("rotation is not proper")
    return matrix


def _r_nv(two_axis: np.ndarray) -> np.ndarray:
    # Global yaw is the one harmless coordinate gauge.  It is fixed to zero;
    # roll/pitch are fitted.  This is a convention, not measured heading.
    return Rotation.from_euler("yx", [float(two_axis[1]), float(two_axis[0])]).as_matrix()


def unpack_static(vector: np.ndarray) -> tuple[np.ndarray, dict[str, np.ndarray], Geometry]:
    vector = np.asarray(vector, float)
    if vector.shape != (2 + 3 * len(SEGMENTS) + len(GEOMETRY_NAMES),):
        raise ValueError("static calibration vector shape mismatch")
    rotation = _r_nv(vector[:2])
    extrinsics = {
        segment: _proper(vector[2 + 3 * i:5 + 3 * i])
        for i, segment in enumerate(SEGMENTS)
    }
    offset = 2 + 3 * len(SEGMENTS)
    geometry = Geometry(*map(float, vector[offset:]))
    return rotation, extrinsics, geometry


def pack_static(rotation_N_from_V4: np.ndarray,
                extrinsics: Mapping[str, np.ndarray], geometry: Geometry) -> np.ndarray:
    euler = Rotation.from_matrix(rotation_N_from_V4).as_euler("yxz")
    values = [np.array([euler[1], euler[0]], float)]
    values.extend(Rotation.from_matrix(extrinsics[name]).as_rotvec() for name in SEGMENTS)
    values.append(geometry.vector())
    return np.concatenate(values)


def segment_rotations(orientation_N_from_B: np.ndarray,
                      extrinsics: Mapping[str, np.ndarray]) -> np.ndarray:
    output = np.empty_like(orientation_N_from_B)
    for index, segment in enumerate(SEGMENTS):
        # R_SB maps B vectors to S; R_BS maps segment vectors to sensor.
        output[:, index] = orientation_N_from_B[:, index] @ extrinsics[segment].T
    return output


def forward_antenna_positions(rotations_N_from_S: np.ndarray, geometry: Geometry) -> np.ndarray:
    """Return antenna locations relative to the Pelvis antenna/root."""
    count = len(rotations_N_from_S); out = np.zeros((count, len(SEGMENTS), 3), float)
    p = SEGMENT_INDEX; g = geometry
    rp = rotations_N_from_S[:, p["Pelvis"]]; rt = rotations_N_from_S[:, p["Torso"]]
    torso_joint = np.einsum("nij,j->ni", rp, [0, 0, g.torso_separation_m / 2])
    torso = torso_joint - np.einsum("nij,j->ni", rt, [0, 0, -g.torso_separation_m / 2])
    out[:, p["Torso"]] = torso

    for side, sign in (("L", -1.0), ("R", 1.0)):
        upper = f"UpperArm_{side}"; fore = f"Forearm_{side}"
        thigh = f"Thigh_{side}"; shank = f"Shank_{side}"
        ru = rotations_N_from_S[:, p[upper]]; rf = rotations_N_from_S[:, p[fore]]
        rth = rotations_N_from_S[:, p[thigh]]; rsh = rotations_N_from_S[:, p[shank]]
        shoulder = torso + np.einsum(
            "nij,j->ni", rt, [sign * g.shoulder_half_width_m, 0, g.shoulder_height_m])
        upper_length = getattr(g, f"upper_arm_{side}_m")
        fore_length = getattr(g, f"forearm_{side}_m")
        elbow = shoulder + np.einsum("nij,j->ni", ru, [0, 0, -upper_length])
        wrist = elbow + np.einsum("nij,j->ni", rf, [0, 0, -fore_length])
        out[:, p[upper]] = elbow; out[:, p[fore]] = wrist

        hip = np.einsum(
            "nij,j->ni", rp, [sign * g.hip_half_width_m, 0, g.hip_vertical_m])
        thigh_length = getattr(g, f"thigh_{side}_m")
        shank_length = getattr(g, f"shank_{side}_m")
        knee = hip + np.einsum("nij,j->ni", rth, [0, 0, -thigh_length])
        ankle = knee + np.einsum("nij,j->ni", rsh, [0, 0, -shank_length])
        out[:, p[thigh]] = knee; out[:, p[shank]] = ankle
    return out


def _whiten(delta: np.ndarray, covariance: np.ndarray) -> np.ndarray:
    try:
        return np.linalg.solve(np.linalg.cholesky(covariance), delta)
    except np.linalg.LinAlgError as error:
        raise ValueError("UWB covariance is not positive definite") from error


class ArticulatedCalibrationProblem:
    """Static batch solve with root translation eliminated at every knot."""
    def __init__(self, samples: CalibrationSamples):
        self.samples = samples
        self.parameter_names = (
            "R_N_from_V4.roll", "R_N_from_V4.pitch",
            *(f"R_{segment}_from_sensor.{axis}" for segment in SEGMENTS for axis in "xyz"),
            *GEOMETRY_NAMES,
        )

    def physical_residual(self, vector: np.ndarray, *, include_actions: frozenset[str] | None = None,
                          include_hinge: bool = True) -> np.ndarray:
        r_nv, extrinsics, geometry = unpack_static(vector)
        rotations = segment_rotations(self.samples.orientation_N_from_B, extrinsics)
        prediction = forward_antenna_positions(rotations, geometry)
        observed = np.einsum("ij,ntj->nti", r_nv, self.samples.position_v4_m)
        pelvis = SEGMENT_INDEX["Pelvis"]
        observed -= observed[:, pelvis:pelvis + 1]
        terms: list[np.ndarray] = []
        for knot in range(len(self.samples.time_ns)):
            if include_actions is not None and str(self.samples.action[knot]) not in include_actions:
                continue
            for segment in range(len(SEGMENTS)):
                if segment == pelvis or not self.samples.valid_position[knot, segment]:
                    continue
                delta = observed[knot, segment] - prediction[knot, segment]
                covariance = (self.samples.covariance_v4_m2[knot, segment]
                              + self.samples.covariance_v4_m2[knot, pelvis])
                terms.append(_whiten(delta, r_nv @ covariance @ r_nv.T))
        if include_hinge:
            for parent, child, _ in HINGES:
                ip = SEGMENT_INDEX[parent]; ic = SEGMENT_INDEX[child]
                relative = np.einsum("nji,njk->nik", rotations[:, ip], rotations[:, ic])
                for knot in range(1, len(relative)):
                    if include_actions is not None and str(self.samples.action[knot]) not in include_actions:
                        continue
                    dt = (int(self.samples.time_ns[knot]) - int(self.samples.time_ns[knot - 1])) / 1e9
                    if dt <= 0 or dt > 0.6 or self.samples.action[knot] != self.samples.action[knot - 1]:
                        continue
                    delta = Rotation.from_matrix(relative[knot - 1].T @ relative[knot]).as_rotvec()
                    terms.append(delta[[0, 2]] / 0.20)
        return np.concatenate(terms) if terms else np.empty(0)

    def residual(self, vector: np.ndarray, *, include_actions: frozenset[str] | None = None) -> np.ndarray:
        physical = self.physical_residual(vector, include_actions=include_actions)
        _, _, geometry = unpack_static(vector)
        prior_mean = np.array([.30, .18, .20, .10, -.05, .30, .25, .30, .25, .43, .40, .43, .40])
        prior_sigma = np.array([.15, .10, .12, .07, .10, .18, .18, .18, .18, .20, .20, .20, .20])
        return np.r_[physical, (geometry.vector() - prior_mean) / prior_sigma]

    @staticmethod
    def bounds() -> tuple[np.ndarray, np.ndarray]:
        rotations = np.full(2 + 3 * len(SEGMENTS), np.pi)
        low_geometry = np.array([.08, .05, -.05, .04, -.20, .12, .12, .12, .12, .18, .15, .18, .15])
        high_geometry = np.array([.70, .40, .50, .30, .15, .65, .60, .65, .60, .80, .75, .80, .75])
        return np.r_[-rotations, low_geometry], np.r_[rotations, high_geometry]

    def solve(self, initial: np.ndarray, *, include_actions: frozenset[str] | None = None,
              max_nfev: int = 250) -> tuple[CalibrationCandidate, object]:
        lower, upper = self.bounds()
        result = least_squares(
            lambda value: self.residual(value, include_actions=include_actions),
            np.clip(initial, lower + 1e-9, upper - 1e-9), bounds=(lower, upper),
            method="trf", loss="soft_l1", f_scale=2.0, max_nfev=max_nfev,
            x_scale="jac", verbose=0,
        )
        r_nv, extrinsics, geometry = unpack_static(result.x)
        candidate = CalibrationCandidate(
            r_nv, extrinsics, geometry, float(result.cost), float(result.optimality),
            int(result.nfev), bool(result.success), str(result.message),
        )
        return candidate, result

    def numerical_jacobian(self, vector: np.ndarray, *, relative_step: float = 2e-6) -> np.ndarray:
        vector = np.asarray(vector, float); baseline = self.physical_residual(vector)
        jacobian = np.empty((len(baseline), len(vector)), float)
        for column in range(len(vector)):
            step = relative_step * max(1.0, abs(float(vector[column])))
            plus = vector.copy(); minus = vector.copy()
            plus[column] += step; minus[column] -= step
            jacobian[:, column] = (
                self.physical_residual(plus) - self.physical_residual(minus)) / (2.0 * step)
        return jacobian


def observability_report(problem: ArticulatedCalibrationProblem, vector: np.ndarray,
                         *, relative_rank_threshold: float = 1e-6) -> dict:
    jacobian = problem.numerical_jacobian(vector)
    _, singular, vt = np.linalg.svd(jacobian, full_matrices=False)
    threshold = float(singular[0] * relative_rank_threshold) if len(singular) else 0.0
    rank = int(np.sum(singular > threshold)); nullity = int(jacobian.shape[1] - rank)
    covariance = np.linalg.pinv(jacobian.T @ jacobian, rcond=relative_rank_threshold)
    sigma = np.sqrt(np.maximum(0.0, np.diag(covariance)))
    _, base_extrinsics, _ = unpack_static(vector)
    null_vectors = []
    finite_null_step = 1e-3
    base_r_nv, base_extrinsics, base_geometry = unpack_static(vector)
    base_rotations = segment_rotations(problem.samples.orientation_N_from_B, base_extrinsics)
    base_prediction = forward_antenna_positions(base_rotations, base_geometry)
    if nullity:
        for ordinal, vector_n in enumerate(vt[rank:]):
            order = np.argsort(np.abs(vector_n))[::-1][:8]
            leading_names = [problem.parameter_names[i] for i in order[:4]]
            geometry_energy = float(sum(vector_n[i] ** 2 for i, name in enumerate(problem.parameter_names)
                                        if name in GEOMETRY_NAMES))
            frame_energy = float(sum(vector_n[i] ** 2 for i, name in enumerate(problem.parameter_names)
                                     if name.startswith("R_N_from_V4")))
            perturbed = np.asarray(vector, float) + finite_null_step * vector_n
            moved_r_nv, moved_extrinsics, moved_geometry = unpack_static(perturbed)
            moved_rotations = segment_rotations(problem.samples.orientation_N_from_B, moved_extrinsics)
            moved_prediction = forward_antenna_positions(moved_rotations, moved_geometry)
            stick_axis_sensitivity = max(
                float(np.linalg.norm(
                    moved_extrinsics[segment].T @ np.array([0., 0., 1.])
                    - base_extrinsics[segment].T @ np.array([0., 0., 1.])) / finite_null_step)
                for segment in SEGMENTS
            )
            segment_axis_change = max(
                float(np.linalg.norm(
                    moved_extrinsics[segment].T @ np.array([0., 0., 1.])
                    - base_extrinsics[segment].T @ np.array([0., 0., 1.])))
                for segment in SEGMENTS
            )
            joint_displacement = float(np.max(np.linalg.norm(
                moved_prediction - base_prediction, axis=2)))
            # With the explicitly fixed endpoint lever prior, these antenna
            # predictions are the same FK points used for joint centres.  Keep
            # both metrics named so a future nonzero lever model cannot hide a
            # body-dimension/lever-arm tradeoff.
            antenna_displacement = joint_displacement
            geometry_change = float(np.max(abs(moved_geometry.vector() - base_geometry.vector())))
            frame_change = float(Rotation.from_matrix(moved_r_nv @ base_r_nv.T).magnitude())
            extrinsic_change = max(float(Rotation.from_matrix(
                moved_extrinsics[segment] @ base_extrinsics[segment].T).magnitude())
                                   for segment in SEGMENTS)
            # A finite 1e-3 perturbation of a first-order numerical null has an
            # expected O(step^2) residual.  The 1e-7 tolerance is therefore a
            # numerical invariance test, not a measurement or freeze gate.
            invariant_tolerance = {"joint_centre_m": 1e-7, "segment_axis_norm": 1e-7,
                                   "antenna_prediction_m": 1e-7, "geometry_m": 1e-7,
                                   "frame_rad": 1e-7}
            if geometry_change > invariant_tolerance["geometry_m"]:
                classification = "GENUINELY_UNOBSERVABLE_BODY_GEOMETRY"
                physical_effect = "body-dimension/lever-arm tradeoff"
            elif (joint_displacement <= invariant_tolerance["joint_centre_m"]
                  and segment_axis_change <= invariant_tolerance["segment_axis_norm"]
                  and antenna_displacement <= invariant_tolerance["antenna_prediction_m"]
                  and frame_change <= invariant_tolerance["frame_rad"]
                  and extrinsic_change > invariant_tolerance["frame_rad"]):
                classification = "LONGITUDINAL_SEGMENT_TWIST_STICK_FIGURE_INVARIANT"
                physical_effect = "segment axial twist only"
            elif frame_change > invariant_tolerance["frame_rad"]:
                classification = "GLOBAL_FRAME_DIRECTION_UNOBSERVABLE"
                physical_effect = "remaining frame gauge"
            elif joint_displacement > invariant_tolerance["joint_centre_m"]:
                classification = "JOINT_CENTRE_UNOBSERVABLE"
                physical_effect = "joint-centre displacement"
            elif segment_axis_change > invariant_tolerance["segment_axis_norm"]:
                classification = "SEGMENT_AXIS_UNOBSERVABLE"
                physical_effect = "segment-axis displacement"
            elif antenna_displacement > invariant_tolerance["antenna_prediction_m"]:
                classification = "ANTENNA_PREDICTION_UNOBSERVABLE"
                physical_effect = "antenna prediction displacement"
            else:
                classification = "SENSOR_SPECIFIC_EXTRINSIC_UNOBSERVABLE"
                physical_effect = "unclassified sensor-extrinsic effect"
            null_vectors.append({
                "index": ordinal, "classification": classification,
                "physical_effect": physical_effect,
                "geometry_energy": geometry_energy,
                "frame_energy": frame_energy,
                "max_stick_axis_sensitivity": stick_axis_sensitivity,
                "finite_perturbation_norm": finite_null_step,
                "finite_effect": {
                    "max_joint_centre_displacement_m": joint_displacement,
                    "max_segment_axis_displacement_norm": segment_axis_change,
                    "max_antenna_prediction_displacement_m": antenna_displacement,
                    "max_body_dimension_change_m": geometry_change,
                    "frame_rotation_change_rad": frame_change,
                    "max_segment_extrinsic_rotation_change_rad": extrinsic_change,
                },
                "invariance_tolerances": invariant_tolerance,
                "full_normalized_null_vector": vector_n.tolist(),
                "components": [
                    {"parameter": problem.parameter_names[i], "coefficient": float(vector_n[i])}
                    for i in order if abs(vector_n[i]) > 1e-4
                ],
            })
    parameter_rows = []
    null_energy = np.sum(vt[rank:] ** 2, axis=0) if nullity else np.zeros(jacobian.shape[1])
    for index, name in enumerate(problem.parameter_names):
        parameter_rows.append({
            "parameter": name, "sigma_linearized": float(sigma[index]),
            "nullspace_energy": float(null_energy[index]),
            "observable": bool(null_energy[index] < 1e-4),
        })
    segment_observability = {}
    for segment in SEGMENTS:
        selected = [row for row in parameter_rows if row["parameter"].startswith(f"R_{segment}_")]
        axis_sensitivity = 0.0
        for null_vector in vt[rank:]:
            perturbed = np.asarray(vector, float) + 1e-5 * null_vector
            _, moved_extrinsics, _ = unpack_static(perturbed)
            before_axis = base_extrinsics[segment].T @ np.array([0.0, 0.0, 1.0])
            after_axis = moved_extrinsics[segment].T @ np.array([0.0, 0.0, 1.0])
            axis_sensitivity = max(axis_sensitivity, float(np.linalg.norm(after_axis - before_axis) / 1e-5))
        segment_observability[segment] = {
            "extrinsic_observable": all(row["observable"] for row in selected),
            "stick_figure_axis_observable": axis_sensitivity < 1e-3,
            "nullspace_axis_sensitivity": axis_sensitivity,
            "max_nullspace_energy": max((row["nullspace_energy"] for row in selected), default=0.0),
        }
    return {
        "jacobian_shape": list(jacobian.shape), "singular_values": singular.tolist(),
        "rank": rank, "columns": jacobian.shape[1], "nullity": nullity,
        "relative_rank_threshold": relative_rank_threshold, "absolute_rank_threshold": threshold,
        "condition_number_identifiable": (float(singular[0] / singular[rank - 1]) if rank else None),
        "fixed_gauge": {
            "dimension": "global yaw", "convention": "R_N_from_V4 yaw = 0",
            "measured_heading": False,
        },
        "nullspace_vectors": null_vectors, "parameters": parameter_rows,
        "per_segment": segment_observability,
    }


def candidate_manifest(candidate: CalibrationCandidate) -> dict:
    g = candidate.geometry
    joint_offsets = {
        "torso_pelvis": {"Pelvis": [0, 0, g.torso_separation_m/2],
                           "Torso": [0, 0, -g.torso_separation_m/2]},
        "shoulder_L": {"Torso": [-g.shoulder_half_width_m, 0, g.shoulder_height_m],
                         "UpperArm_L": [0, 0, 0]},
        "shoulder_R": {"Torso": [g.shoulder_half_width_m, 0, g.shoulder_height_m],
                         "UpperArm_R": [0, 0, 0]},
        "elbow_L": {"UpperArm_L": [0, 0, -g.upper_arm_L_m], "Forearm_L": [0, 0, 0]},
        "elbow_R": {"UpperArm_R": [0, 0, -g.upper_arm_R_m], "Forearm_R": [0, 0, 0]},
        "hip_L": {"Pelvis": [-g.hip_half_width_m, 0, g.hip_vertical_m], "Thigh_L": [0, 0, 0]},
        "hip_R": {"Pelvis": [g.hip_half_width_m, 0, g.hip_vertical_m], "Thigh_R": [0, 0, 0]},
        "knee_L": {"Thigh_L": [0, 0, -g.thigh_L_m], "Shank_L": [0, 0, 0]},
        "knee_R": {"Thigh_R": [0, 0, -g.thigh_R_m], "Shank_R": [0, 0, 0]},
    }
    return {
        "R_N_from_V4": np.asarray(candidate.R_N_from_V4).tolist(),
        "R_V4_from_N": np.asarray(candidate.R_N_from_V4).T.tolist(),
        "R_segment_from_sensor": {
            key: np.asarray(value).tolist() for key, value in candidate.R_segment_from_sensor.items()
        },
        "geometry": asdict(candidate.geometry), "cost": candidate.cost,
        "joint_centre_offsets_segment_m": joint_offsets,
        "hinge_axes_segment": {
            "elbow_L": [0, 1, 0], "elbow_R": [0, 1, 0],
            "knee_L": [0, 1, 0], "knee_R": [0, 1, 0],
        },
        "optimality": candidate.optimality, "iterations": candidate.iterations,
        "success": candidate.success, "message": candidate.message,
        "antenna_lever_contract": {
            "Pelvis/Torso": "fixed zero at segment reference origin",
            "limbs": "fixed placement prior at distal endpoint; uncertainty remains in UWB covariance",
            "status": "MVP_PRIOR_NOT_ANATOMICAL_SURVEY",
        },
    }


def initial_static_guess(samples: CalibrationSamples) -> np.ndarray:
    """Data-derived initialization; no held-out values or subject dimensions."""
    p = SEGMENT_INDEX; position = samples.position_v4_m
    tpose = samples.action == "t_pose"
    usable = tpose if np.any(tpose) else np.ones(len(samples.time_ns), bool)
    median = np.nanmedian(np.where(samples.valid_position[..., None], position, np.nan)[usable], axis=0)
    if not np.isfinite(median).all():
        missing = [SEGMENTS[index] for index in np.flatnonzero(~np.isfinite(median).all(axis=1))]
        raise ValueError(f"T-Pose initialization lacks finite segment positions: {missing}")
    vertical = median[p["Torso"]] - median[p["Pelvis"]]
    lateral = ((median[p["UpperArm_R"]] + median[p["Forearm_R"]])
               - (median[p["UpperArm_L"]] + median[p["Forearm_L"]]))
    vertical /= np.linalg.norm(vertical); lateral -= vertical * float(lateral @ vertical)
    lateral /= np.linalg.norm(lateral); forward = np.cross(lateral, vertical)
    forward /= np.linalg.norm(forward)
    source = np.column_stack([lateral, forward, vertical])
    if np.linalg.det(source) < 0:
        source[:, 1] *= -1
    r_nv = source.T

    direct = lambda a, b: float(np.nanmedian(np.linalg.norm(position[usable, p[b]] - position[usable, p[a]], axis=1)))
    geometry = Geometry(
        torso_separation_m=float(np.clip(direct("Pelvis", "Torso"), .10, .60)),
        shoulder_half_width_m=.16, shoulder_height_m=.10,
        hip_half_width_m=.09, hip_vertical_m=-.03,
        upper_arm_L_m=float(np.clip(direct("Torso", "UpperArm_L") - .16, .15, .55)),
        forearm_L_m=float(np.clip(direct("UpperArm_L", "Forearm_L"), .15, .55)),
        upper_arm_R_m=float(np.clip(direct("Torso", "UpperArm_R") - .16, .15, .55)),
        forearm_R_m=float(np.clip(direct("UpperArm_R", "Forearm_R"), .15, .55)),
        thigh_L_m=float(np.clip(direct("Pelvis", "Thigh_L") - .08, .20, .70)),
        shank_L_m=float(np.clip(direct("Thigh_L", "Shank_L"), .18, .70)),
        thigh_R_m=float(np.clip(direct("Pelvis", "Thigh_R") - .08, .20, .70)),
        shank_R_m=float(np.clip(direct("Thigh_R", "Shank_R"), .18, .70)),
    )

    target_z = {
        "Pelvis": vertical, "Torso": vertical,
        "UpperArm_L": -(median[p["UpperArm_L"]] - median[p["Torso"]]),
        "Forearm_L": -(median[p["Forearm_L"]] - median[p["UpperArm_L"]]),
        "UpperArm_R": -(median[p["UpperArm_R"]] - median[p["Torso"]]),
        "Forearm_R": -(median[p["Forearm_R"]] - median[p["UpperArm_R"]]),
        "Thigh_L": -(median[p["Thigh_L"]] - median[p["Pelvis"]]),
        "Shank_L": -(median[p["Shank_L"]] - median[p["Thigh_L"]]),
        "Thigh_R": -(median[p["Thigh_R"]] - median[p["Pelvis"]]),
        "Shank_R": -(median[p["Shank_R"]] - median[p["Thigh_R"]]),
    }
    orientation = samples.orientation_N_from_B[usable]
    extrinsics = {}
    for segment in SEGMENTS:
        z_n = r_nv @ target_z[segment]
        if not np.isfinite(z_n).all() or np.linalg.norm(z_n) < 1e-8:
            raise ValueError(f"degenerate T-Pose segment axis: {segment}")
        z_n /= np.linalg.norm(z_n)
        q = Rotation.from_matrix(orientation[:, p[segment]]).mean().as_matrix()
        z_b = q.T @ z_n
        r_bs, _ = Rotation.align_vectors(np.asarray([z_b]), np.asarray([[0.0, 0.0, 1.0]]))
        extrinsics[segment] = r_bs.as_matrix().T
    return pack_static(r_nv, extrinsics, geometry)
