#!/usr/bin/env bash
set -euo pipefail

build_dir="${1:-build-alt-bcast-b70-cir-feature-tag-g1200-r1000}"

export APP_TAG_FW_MARKER="${APP_TAG_FW_MARKER:-alt-bcast-b70-cir-feature-g1200-r1000}"

export APP_ALT_SS_TWR_ENABLE=1
export APP_ALT_SS_TWR_BCAST_ENABLE=1
export APP_ALT_SS_TWR_MODE=2
export APP_ALT_SS_TWR_GUARD_US="${APP_ALT_SS_TWR_GUARD_US:-1200}"
export APP_ALT_SS_TWR_RESP_SPACING_US="${APP_ALT_SS_TWR_RESP_SPACING_US:-1000}"
export APP_ALT_SS_TWR_BCAST_FORCE_FULL_SWEEP="${APP_ALT_SS_TWR_BCAST_FORCE_FULL_SWEEP:-1}"
export APP_ALT_SS_TWR_LIGHT_TDMA_ENABLE="${APP_ALT_SS_TWR_LIGHT_TDMA_ENABLE:-1}"
export APP_ALT_SS_TWR_BCAST_IMMEDIATE_TX_ENABLE="${APP_ALT_SS_TWR_BCAST_IMMEDIATE_TX_ENABLE:-1}"
export APP_ALT_SS_TWR_BCAST_PREWRITE_TX_ENABLE="${APP_ALT_SS_TWR_BCAST_PREWRITE_TX_ENABLE:-1}"

export APP_TAG_TDMA_SLOT_PERIOD_MS="${APP_TAG_TDMA_SLOT_PERIOD_MS:-20}"
export APP_TAG_TDMA_SLOT_ACTIVE_MS="${APP_TAG_TDMA_SLOT_ACTIVE_MS:-18}"
export APP_TAG_TDMA_SLOT_ACTIVE_US="${APP_TAG_TDMA_SLOT_ACTIVE_US:-0}"

export APP_TAG_NORMAL_OUTPUT_ENABLE=0
export APP_TAG_CIR_FEATURE_OUTPUT_ENABLE=1
export APP_TAG_CIR_FEATURE_OUTPUT_BLE_ENABLE="${APP_TAG_CIR_FEATURE_OUTPUT_BLE_ENABLE:-1}"
export APP_TAG_TRACK_ANCHOR_COUNT="${APP_TAG_TRACK_ANCHOR_COUNT:-8}"

export APP_TAG_TR_IMU_SUMMARY_ENABLE=0
export APP_TAG_TR_IMU_RAW_ENABLE=0
export APP_TAG_BCAST_SUMMARY_ENABLE=0
export APP_TAG_CONSOLE_SUMMARY_ENABLE=0
export APP_TAG_VERBOSE_PERF=0
export APP_TAG_PENDING_PRINT_PERIOD=0
export APP_TAG_SWEEP_DIAG_ENABLE=0
export APP_TAG_ALT_RXG_BLE_DIAG_ENABLE=0
export APP_TAG_IMU_SAMPLE_PERIOD=255

exec scripts/build_tag_ble_motion.sh 0 10 "${build_dir}"
