# —— Bluetooth 栈 ——  
CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_SCAN=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_GATT_DM=y
CONFIG_BT_NUS_CLIENT=y
CONFIG_BT_SMP=y
CONFIG_BT_BONDABLE=y

# —— 并发连接数（SoftDevice 最大 8，示例设 4） ——  
CONFIG_BT_MAX_CONN=4

# —— PHY / MTU / 数据长度 ——  
# SoftDevice S112/S132 在 Zephyr v3.7.99 下仅支持 <= 69  
CONFIG_BT_CTLR_PHY_2M=y
# 把 DATA_LENGTH_MAX 降到 69，别再用 251，否则范围外会被忽略  
CONFIG_BT_CTLR_DATA_LENGTH_MAX=69  
CONFIG_BT_L2CAP_TX_MTU=247

# —— Persistent Bond/Pairing ——  
# 用 Zephyr 默认的 BT_SETTINGS，把配对信息存在 Controller NVM  
CONFIG_BT_SETTINGS=y

# —— 日志 & Shell ——  
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_BT_SHELL=y

# —— Console / UART ——  
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PINCTRL=y

# —— 动态内存 & GPIO ——  
CONFIG_HEAP_MEM_POOL_SIZE=1024
CONFIG_GPIO=y
