"""Independent geometric cases, not poses generated by the fitted inverse rig."""
import copy

import numpy as np
import pytest
import torch
from scipy.spatial.transform import Rotation

from biospur_fusion.c2_five_calibration.body_feasibility import (
    BodyFeasibility, SCHEMA, segment_core_depth, selection_key, relative_coordinates, make_body_spec)
from biospur_fusion.c2_five_calibration.solver import PoseObjective, solve_pose
from test_c2_joint_kinematics import geometry


def rig():
    g=geometry()
    offsets=np.asarray(g['rest_offsets_m'])
    offsets[3]=[0,.1,0];offsets[6]=[0,.15,0];offsets[9]=[0,.15,0]
    offsets[13]=[.08,.04,0];offsets[14]=[-.08,.04,0]
    offsets[16]=[.12,.01,0];offsets[17]=[-.12,.01,0]
    g['rest_offsets_m']=offsets.tolist()
    g['body_feasibility']=dict(schema=SCHEMA,anchor_joint=3,rotation_joint=9,
        centre_from_anchor_m=[0,.175,0],inner_radii_m=[.14,.18,.075],
        outer_radii_m=[.18,.21,.1],penetration_tolerance_m=.002,
        collision_scale_m=.02,collision_weight=10.,torso_swing_soft_deg=90.,
        torso_twist_soft_deg=100.,angular_scale_deg=20.,shoulder_posterior_soft_deg=70.,angular_weight=.2)
    return g


def test_exact_segment_crossing_outside_endpoints_and_touching():
    centre=torch.zeros(3,dtype=torch.float64);radii=torch.tensor([.2,.3,.1])
    a=torch.tensor([[-1.,0,0],[-1.,0,.1],[-1.,0,.12]],dtype=torch.float64)
    b=a.clone();b[:,0]=1.
    result=segment_core_depth(a,b,centre,radii)
    np.testing.assert_allclose(result,[.1,0,0],atol=1e-8)


def test_straight_segment_point_limit_and_finite_gradient():
    a=torch.tensor([[.03,.04,.02]],dtype=torch.float64,requires_grad=True)
    d=segment_core_depth(a,a,torch.zeros(3),torch.tensor([.2,.3,.1]))
    d.sum().backward()
    assert d.item()>0 and torch.isfinite(a.grad).all() and a.grad.abs().sum()>0


def poses():
    r=torch.eye(3,dtype=torch.float64).repeat(2,24,1,1)
    # Same four distal rotations. Left upper arm either hangs outside the
    # torso or points diagonally through it. Right arm remains hanging.
    r[:,17]=torch.tensor(Rotation.from_euler('z',90,degrees=True).as_matrix())
    r[0,16]=torch.tensor(Rotation.from_euler('z',-90,degrees=True).as_matrix())
    r[1,16]=torch.tensor(Rotation.from_euler('z',-140,degrees=True).as_matrix())
    r[:,18]=torch.tensor(Rotation.from_euler('z',-90,degrees=True).as_matrix())
    r[:,19]=r[:,17]
    return r


def test_same_distal_observations_do_not_make_body_states_equally_valid():
    r=poses();b=BodyFeasibility(rig());valid=torch.ones(2,dtype=torch.bool)
    t=b.evaluate(r,valid)
    assert t['inner_depth_proxy_m'][0].max()<1e-12
    assert t['inner_depth_proxy_m'][1,0]>.002
    assert torch.equal(r[0,[0,18,19,4,5]],r[1,[0,18,19,4,5]])


def test_global_rotation_invariance_and_horizontal_twist_singularity():
    r=poses();b=BodyFeasibility(rig());valid=torch.ones(2,dtype=torch.bool)
    w=torch.tensor(Rotation.from_rotvec([.4,-1.2,.6]).as_matrix())
    a,c=b.evaluate(r,valid),b.evaluate(w@r,valid)
    torch.testing.assert_close(a['body_loss'],c['body_loss'])
    torch.testing.assert_close(a['inner_depth_proxy_m'],c['inner_depth_proxy_m'])
    r[:,9]=torch.tensor(Rotation.from_euler('z',90,degrees=True).as_matrix())
    r.requires_grad_();_,coords=relative_coordinates(r,rig())
    coords['torso_twist_rad'].sum().backward()
    assert torch.isfinite(r.grad).all()


def test_crossed_forearm_in_front_is_not_penetration():
    # Analytic volume coordinates: crossing the midline anterior to the
    # body is legal. Crossing the same line through the body is not.
    radii=torch.tensor([.14,.18,.075]);centre=torch.zeros(3)
    front=segment_core_depth(torch.tensor([.3,0,.13]),torch.tensor([-.3,0,.13]),centre,radii)
    through=segment_core_depth(torch.tensor([.3,0,0.]),torch.tensor([-.3,0,0.]),centre,radii)
    assert front==0 and through>.002


def test_feasibility_precedes_low_loss_and_bad_geometry_is_rejected():
    assert selection_key(100,0)<selection_key(0,.01)
    assert selection_key(100,.005)<selection_key(0,.01)
    g=rig();g['body_feasibility']['inner_radii_m']=[-1,1,1]
    with pytest.raises(ValueError,match='radii'):BodyFeasibility(g)


def test_body_owner_is_used_in_pose_objective_without_changing_measurements():
    g=rig();r=poses()[1:2].repeat(60,1,1,1).numpy()
    q=dict(prior=r,observed=r[:,[0,18,19,4,5]],acceleration=np.zeros((60,5,3)),
           valid=np.ones(60,bool),time_s=np.arange(60)/20)
    o=PoseObjective(**q,geometry=g);p=o.initial.clone()
    _,terms=o.evaluate(p,np.zeros((5,3)))
    plain=copy.deepcopy(g);plain.pop('body_feasibility')
    base=PoseObjective(**q,geometry=plain)
    _,before=base.evaluate(p,np.zeros((5,3)))
    torch.testing.assert_close(terms['loss']-before['loss'],terms['body_loss'])
    result,audit=solve_pose(**q,geometry=g,levers=np.zeros((5,3)),iterations=2)
    np.testing.assert_array_equal(result[:,[0,18,19,4,5]],q['observed'])
    assert audit['body_feasibility']['enabled']


def test_external_width_changes_envelope_without_changing_joint_centres():
    g=rig();positions=[]
    for i,p in enumerate(g['parent']):
        positions.append(np.zeros(3) if i==0 else positions[p]+np.asarray(g['rest_offsets_m'][i]))
    g['rest_joints_m']=np.array(positions).tolist()
    a=np.linspace(0,2*np.pi,60,endpoint=False)
    skin=np.array([[.15*np.cos(x),y,.09*np.sin(x)] for y in np.linspace(.12,.39,12) for x in a])
    surface=dict(measurements=[dict(measurement_id='biacromial_breadth',observations=[dict(value_mm=400)])])
    before=copy.deepcopy(g)
    first=make_body_spec(g,skin,surface)
    surface['measurements'][0]['observations'][0]['value_mm']=440
    second=make_body_spec(g,skin,surface)
    assert g==before
    assert second['outer_radii_m'][0]>first['outer_radii_m'][0]
    assert second['outer_radii_m'][1:]==first['outer_radii_m'][1:]


def test_left_right_correspondence_without_forcing_symmetric_motion():
    g=rig();r=poses();mirror=torch.diag(torch.tensor([-1.,1.,1.],dtype=torch.float64))
    permutation=list(range(24))
    for a,b in ((1,2),(4,5),(7,8),(10,11),(13,14),(16,17),(18,19),(20,21),(22,23)):
        permutation[a],permutation[b]=b,a
    reflected=mirror@r[:,permutation]@mirror
    b=BodyFeasibility(g);v=torch.ones(2,dtype=torch.bool)
    a,c=b.evaluate(r,v),b.evaluate(reflected,v)
    torch.testing.assert_close(a['inner_depth_proxy_m'][:,[2,3,0,1]],c['inner_depth_proxy_m'])
