# Auto-generated by verify_anchor_mapping.py. Do not edit by hand.
ANCHOR_ID_TO_LABEL = {0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E', 5: 'F', 6: 'G', 7: 'H'}
ANCHOR_LABEL_TO_ID = {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7}
MAPPING_VERIFICATION = {'best_cost': 7383510.759850063, 'second_best_cost': 10924080.545021206, 'best_rms_mm': 196.10146661244636, 'second_best_rms_mm': 238.52935424943428, 'second_over_best_cost_ratio': 1.4795238877992833}
