"""Bounded articulated raw-range update around the frozen C2 FK proxy.

This module is deliberately an incremental IK layer, not a replacement body
model.  Frozen segment attitudes are the orientation observations; the only
free pose variables are one world root and small right-multiplicative segment
corrections.  All tag points are regenerated by the same FK tree on every
residual evaluation, so UWB cannot move ten nodes independently.

The C2 display geometry remains a diagnostic proxy rather than anatomical
joint-centre or antenna phase-centre metrology.  Consequently this solver can
qualify the fusion mechanism but cannot by itself create a scientific pass.
"""
from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Any, Callable, Mapping, Sequence

import numpy as np
from scipy.optimize import least_squares
from scipy.spatial.transform import Rotation

from biospur_fusion.c2_3a_kinematics.interface import DisplayProxyGeometry

from .frozen_body_proxy import NODE_TO_PROXY_POINT
from .shared_root import SharedRangeLink


SEGMENTS = (
    "pelvis", "torso", "upper_arm_left", "forearm_left",
    "upper_arm_right", "forearm_right", "thigh_left", "shank_left",
    "thigh_right", "shank_right",
)


@dataclass(frozen=True)
class ArticulatedRangeConfig:
    root_prior_sigma_m: float = 0.08
    orientation_prior_sigma_rad: float = 0.10
    temporal_orientation_sigma_rad: float = 0.08
    huber_threshold_sigma: float = 2.5
    positive_nlos_scale_m: float = 0.20
    maximum_root_step_m: float = 0.08
    maximum_segment_correction_rad: float = 0.18
    # Twenty-four evaluations was one iteration short for otherwise
    # well-conditioned elbow epochs (root-Jacobian condition about 5--6).
    # Keep a hard bound, but allow those solves to reach convergence.
    maximum_nfev: int = 32

    def validate(self) -> None:
        positive = (
            self.root_prior_sigma_m,
            self.orientation_prior_sigma_rad,
            self.temporal_orientation_sigma_rad,
            self.huber_threshold_sigma,
            self.positive_nlos_scale_m,
            self.maximum_root_step_m,
            self.maximum_segment_correction_rad,
        )
        if not all(math.isfinite(value) and value > 0.0 for value in positive):
            raise ValueError("articulated range scales must be finite and positive")
        if self.maximum_nfev < 1:
            raise ValueError("articulated solve needs at least one function evaluation")


@dataclass(frozen=True)
class ArticulatedRangeResult:
    success: bool
    reason: str
    root_position_m: np.ndarray
    segment_correction_rotvec: Mapping[str, np.ndarray]
    node_position_m: Mapping[str, np.ndarray]
    prefit_physical_residual_m: np.ndarray
    physical_residual_m: np.ndarray
    effective_weight: np.ndarray
    facing_nlos_weight: np.ndarray
    root_covariance_m2: np.ndarray
    rank: int
    condition: float
    nfev: int
    cost: float
    maximum_joint_closure_m: float
    active_segments: tuple[str, ...]
    pose_observable_rank: int
    hinge_projection: Mapping[str, Any]


NODE_KINEMATIC_PATHS = {
    "BSF31CC": ("torso",),
    "BSFC2CC": (),
    "BSFAA61": ("torso", "upper_arm_left"),
    "BSF1120": ("torso", "upper_arm_right"),
    "BSFEC35": ("torso", "upper_arm_left", "forearm_left"),
    "BSFB165": ("torso", "upper_arm_right", "forearm_right"),
    "BSF44AD": ("pelvis", "thigh_left"),
    "BSF3C79": ("pelvis", "thigh_right"),
    "BSF6C53": ("pelvis", "thigh_left", "shank_left"),
    "BSF8BC4": ("pelvis", "thigh_right", "shank_right"),
}


def active_segments_for_nodes(nodes: Sequence[str]) -> tuple[str, ...]:
    """Return only kinematic paths capable of moving observed tag points."""

    unknown = set(nodes) - set(NODE_KINEMATIC_PATHS)
    if unknown:
        raise ValueError(f"unknown C2 body nodes: {sorted(unknown)}")
    active = {
        segment
        for node in nodes
        for segment in NODE_KINEMATIC_PATHS[str(node)]
    }
    return tuple(segment for segment in SEGMENTS if segment in active)


def corrected_proxy_points(
    base_rotations_world: Mapping[str, np.ndarray],
    correction_rotvec: Mapping[str, np.ndarray],
    geometry: DisplayProxyGeometry,
) -> dict[str, np.ndarray]:
    """Evaluate the exact frozen display-proxy tree after small corrections."""

    missing = set(SEGMENTS) - set(base_rotations_world)
    if missing:
        raise ValueError(f"missing base segment rotations: {sorted(missing)}")
    rotations = {}
    for segment in SEGMENTS:
        base = np.asarray(base_rotations_world[segment], dtype=float).reshape(3, 3)
        delta = np.asarray(correction_rotvec[segment], dtype=float).reshape(3)
        if not np.all(np.isfinite(base)) or not np.all(np.isfinite(delta)):
            raise ValueError("segment rotations must be finite")
        rotations[segment] = base @ Rotation.from_rotvec(delta).as_matrix()

    length = geometry.segment_length_m
    root = np.zeros(3)
    shoulder_mid = rotations["torso"] @ np.array([0.0, 0.0, geometry.torso_height_m])
    shoulder_left = shoulder_mid + rotations["torso"] @ np.array(
        [-0.5 * geometry.shoulder_span_m, 0.0, 0.0]
    )
    shoulder_right = shoulder_mid + rotations["torso"] @ np.array(
        [0.5 * geometry.shoulder_span_m, 0.0, 0.0]
    )
    hip_left = rotations["pelvis"] @ np.array(
        [-0.5 * geometry.hip_span_m, 0.0, 0.0]
    )
    hip_right = rotations["pelvis"] @ np.array(
        [0.5 * geometry.hip_span_m, 0.0, 0.0]
    )
    elbow_left = shoulder_left + rotations["upper_arm_left"] @ np.array(
        [0.0, 0.0, -length["upper_arm_left"]]
    )
    wrist_left = elbow_left + rotations["forearm_left"] @ np.array(
        [0.0, 0.0, -length["forearm_left"]]
    )
    elbow_right = shoulder_right + rotations["upper_arm_right"] @ np.array(
        [0.0, 0.0, -length["upper_arm_right"]]
    )
    wrist_right = elbow_right + rotations["forearm_right"] @ np.array(
        [0.0, 0.0, -length["forearm_right"]]
    )
    knee_left = hip_left + rotations["thigh_left"] @ np.array(
        [0.0, 0.0, -length["thigh_left"]]
    )
    ankle_left = knee_left + rotations["shank_left"] @ np.array(
        [0.0, 0.0, -length["shank_left"]]
    )
    knee_right = hip_right + rotations["thigh_right"] @ np.array(
        [0.0, 0.0, -length["thigh_right"]]
    )
    ankle_right = knee_right + rotations["shank_right"] @ np.array(
        [0.0, 0.0, -length["shank_right"]]
    )
    return {
        "pelvis_center": root,
        "shoulder_mid": shoulder_mid,
        "shoulder_left": shoulder_left,
        "shoulder_right": shoulder_right,
        "hip_left": hip_left,
        "hip_right": hip_right,
        "elbow_left": elbow_left,
        "wrist_left": wrist_left,
        "elbow_right": elbow_right,
        "wrist_right": wrist_right,
        "knee_left": knee_left,
        "ankle_left": ankle_left,
        "knee_right": knee_right,
        "ankle_right": ankle_right,
    }


def _failure(reason: str, root: np.ndarray) -> ArticulatedRangeResult:
    corrections = {segment: np.zeros(3) for segment in SEGMENTS}
    return ArticulatedRangeResult(
        False, reason, np.asarray(root, float).copy(), corrections, {},
        np.empty(0), np.empty(0), np.empty(0), np.empty(0), np.eye(3) * math.inf,
        0, math.inf, 0, math.inf, math.inf, (), 0, {},
    )


def solve_articulated_ranges(
    links: Sequence[SharedRangeLink],
    *,
    anchors_m: np.ndarray,
    base_rotations_world: Mapping[str, np.ndarray],
    geometry: DisplayProxyGeometry,
    initial_root_m: np.ndarray,
    root_velocity_mps: np.ndarray | None = None,
    previous_correction_rotvec: Mapping[str, np.ndarray] | None = None,
    active_segments: Sequence[str] | None = None,
    point_constraints_world_m: Mapping[str, np.ndarray] | None = None,
    point_constraint_sigma_m: float = 0.03,
    point_constraint_axes: Sequence[int] = (0, 1, 2),
    use_facing_nlos_prior: bool = True,
    hinge_projector: Callable[
        [Mapping[str, np.ndarray], Mapping[str, np.ndarray]],
        tuple[dict[str, np.ndarray], dict[str, Any]],
    ] | None = None,
    config: ArticulatedRangeConfig = ArticulatedRangeConfig(),
) -> ArticulatedRangeResult:
    """Solve raw ranges against one FK-connected body at one UWB epoch."""

    config.validate()
    root0 = np.asarray(initial_root_m, float).reshape(3)
    velocity = np.zeros(3) if root_velocity_mps is None else np.asarray(
        root_velocity_mps, float
    ).reshape(3)
    anchors = np.asarray(anchors_m, float)
    if anchors.shape != (8, 3) or not np.isfinite(anchors).all():
        raise ValueError("anchors_m must be a finite canonical 8x3 layout")
    if len(links) < 4:
        return _failure("FEWER_THAN_FOUR_LINKS", root0)
    if not math.isfinite(point_constraint_sigma_m) or point_constraint_sigma_m <= 0.0:
        raise ValueError("point constraint sigma must be finite and positive")
    constraint_axes = tuple(int(axis) for axis in point_constraint_axes)
    if not constraint_axes or len(set(constraint_axes)) != len(constraint_axes):
        raise ValueError("point constraint axes must be unique and nonempty")
    if set(constraint_axes) - {0, 1, 2}:
        raise ValueError("point constraint axes must be drawn from x/y/z")
    identities = {(str(link.node), int(link.anchor)) for link in links}
    if len(identities) != len(links):
        return _failure("DUPLICATE_NODE_ANCHOR_LINK", root0)
    previous = {
        segment: np.zeros(3) if previous_correction_rotvec is None else np.asarray(
            previous_correction_rotvec[segment], float
        ).reshape(3)
        for segment in SEGMENTS
    }
    active = (
        tuple(SEGMENTS)
        if active_segments is None
        else tuple(dict.fromkeys(str(segment) for segment in active_segments))
    )
    if set(active) - set(SEGMENTS):
        raise ValueError("active_segments contains an unknown segment")
    anchor_rows = np.asarray([anchors[int(link.anchor)] for link in links])
    measured = np.asarray([link.range_m for link in links], float)
    sigma = np.asarray([link.sigma_m for link in links], float)
    link_dt = np.asarray([link.link_dt_s for link in links], float)
    facing = np.asarray([
        0.0 if link.facing_score is None else float(link.facing_score)
        for link in links
    ])
    if not (
        np.isfinite(root0).all() and np.isfinite(velocity).all()
        and np.isfinite(measured).all() and np.isfinite(sigma).all()
        and np.all(measured > 0.0) and np.all(sigma > 0.0)
        and np.all((-1.0 <= facing) & (facing <= 1.0))
    ):
        raise ValueError("invalid articulated range input")

    x0 = np.r_[root0, *(previous[segment] for segment in active)]
    point_constraints = {
        str(name): np.asarray(target, dtype=float).reshape(3)
        for name, target in (point_constraints_world_m or {}).items()
    }
    valid_point_names = set(corrected_proxy_points(
        base_rotations_world, previous, geometry
    ))
    if set(point_constraints) - valid_point_names:
        raise ValueError("point constraint names are outside the FK proxy")
    if any(not np.isfinite(target).all() for target in point_constraints.values()):
        raise ValueError("point constraint targets must be finite")

    def decode_raw(vector: np.ndarray) -> tuple[np.ndarray, dict[str, np.ndarray]]:
        corrections = {segment: previous[segment].copy() for segment in SEGMENTS}
        corrections.update({
            segment: vector[3 + 3 * index:6 + 3 * index]
            for index, segment in enumerate(active)
        })
        return vector[:3], corrections

    def physical_from(
        root: np.ndarray, corrections: Mapping[str, np.ndarray]
    ) -> tuple[np.ndarray, dict[str, np.ndarray]]:
        points = corrected_proxy_points(base_rotations_world, corrections, geometry)
        node_positions = {
            node: root + points[point]
            for node, point in NODE_TO_PROXY_POINT.items()
        }
        predicted = np.asarray([
            np.linalg.norm(
                anchor_rows[index]
                - (
                    node_positions[link.node]
                    + link_dt[index] * velocity
                )
            )
            for index, link in enumerate(links)
        ])
        return measured - predicted, node_positions

    def physical(vector: np.ndarray) -> tuple[np.ndarray, dict[str, np.ndarray]]:
        root, corrections = decode_raw(vector)
        return physical_from(root, corrections)

    def weights(innovation: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        standardized = np.abs(innovation / sigma)
        robust = np.ones_like(standardized)
        outside = standardized > config.huber_threshold_sigma
        robust[outside] = config.huber_threshold_sigma / standardized[outside]
        facing_weight = np.ones_like(robust)
        if use_facing_nlos_prior:
            # A sign-compatible residual inside nominal noise is not evidence
            # of obstruction.  Require one nominal standard deviation before
            # antenna orientation can reduce information.
            positive = innovation > sigma
            inward_probability = 0.5 * (1.0 - facing[positive])
            ratio = innovation[positive] / config.positive_nlos_scale_m
            # Orientation alone never changes a link.  It can reduce influence
            # only when the observed sign also matches body-shadow NLOS.
            facing_weight[positive] = 1.0 / (
                1.0 + inward_probability * np.square(ratio)
            )
        return robust * facing_weight, facing_weight

    def residual(vector: np.ndarray) -> np.ndarray:
        innovation, _ = physical(vector)
        effective, _ = weights(innovation)
        root, corrections = decode_raw(vector)
        terms = [
            np.sqrt(effective) * innovation / sigma,
            (root - root0) / config.root_prior_sigma_m,
        ]
        terms.extend(
            corrections[segment] / config.orientation_prior_sigma_rad
            for segment in active
        )
        terms.extend(
            (corrections[segment] - previous[segment])
            / config.temporal_orientation_sigma_rad
            for segment in active
        )
        if point_constraints:
            points = corrected_proxy_points(
                base_rotations_world, corrections, geometry
            )
            terms.extend(
                (root + points[name] - target)[list(constraint_axes)]
                / point_constraint_sigma_m
                for name, target in point_constraints.items()
            )
        return np.concatenate(terms)

    lower = np.r_[
        root0 - config.maximum_root_step_m,
        np.full(3 * len(active), -config.maximum_segment_correction_rad),
    ]
    upper = np.r_[
        root0 + config.maximum_root_step_m,
        np.full(3 * len(active), config.maximum_segment_correction_rad),
    ]
    try:
        prefit_innovation, _ = physical(x0)
        optimized = least_squares(
            residual, np.clip(x0, lower, upper), bounds=(lower, upper),
            method="trf", loss="linear", x_scale="jac",
            max_nfev=config.maximum_nfev,
        )
        root, raw_corrections = decode_raw(optimized.x)
        raw_innovation, _ = physical_from(root, raw_corrections)
        physical_jacobian = optimized.jac[:len(links)]
        hessian = optimized.jac.T @ optimized.jac
        covariance = np.linalg.pinv(hessian, rcond=1e-10)[:3, :3]
        covariance += np.eye(3) * 0.12**2
        pose_jacobian = physical_jacobian[:, 3:]
        if pose_jacobian.shape[1]:
            # `optimized.jac` is the Jacobian of the weighted residual used by
            # the raw solve.  Project pose columns against its matching root
            # columns here; the physical projected-root observability gate is
            # recomputed independently below after the hinge projection.
            root_basis = np.linalg.qr(
                physical_jacobian[:, :3], mode="reduced"
            )[0]
            projected = pose_jacobian - root_basis @ (
                root_basis.T @ pose_jacobian
            )
            pose_singular = np.linalg.svd(projected, compute_uv=False)
            pose_tolerance = (
                pose_singular[0] * 1e-3 if len(pose_singular) else math.inf
            )
            pose_rank = int(np.sum(pose_singular > pose_tolerance))
        else:
            pose_rank = 0
    except (ValueError, FloatingPointError, np.linalg.LinAlgError):
        return _failure("NUMERICAL_FAILURE", root0)

    projection_metrics: Mapping[str, Any] = {}
    if hinge_projector is not None:
        corrections, projection_metrics = hinge_projector(
            base_rotations_world, raw_corrections
        )
    else:
        corrections = raw_corrections
    innovation, node_positions = physical_from(root, corrections)
    effective, facing_weight = weights(innovation)
    projected_tag = np.asarray([
        node_positions[link.node] + link_dt[index] * velocity
        for index, link in enumerate(links)
    ])
    projected_delta = anchor_rows - projected_tag
    projected_distance = np.linalg.norm(projected_delta, axis=1)
    root_jacobian = projected_delta / projected_distance[:, None]
    singular = np.linalg.svd(root_jacobian, compute_uv=False)
    tolerance = singular[0] * 1e-8 if len(singular) else math.inf
    rank = int(np.sum(singular > tolerance))
    condition = (
        float(np.linalg.cond(root_jacobian.T @ root_jacobian))
        if rank == 3 else math.inf
    )
    max_correction = max(float(np.linalg.norm(value)) for value in corrections.values())
    prefit_median = float(np.median(np.abs(prefit_innovation)))
    raw_median = float(np.median(np.abs(raw_innovation)))
    projected_median = float(np.median(np.abs(innovation)))
    projection_inside = bool(
        not projection_metrics
        or projection_metrics.get("post_projection_all_inside_rom") is True
    )
    projection_applied = hinge_projector is not None
    # A post-solve projection is not an optimizer iterate.  Without point
    # constraints retain the established range-only monotonic gate exactly.
    # With footholds, range and contact are deliberately competing terms, so
    # range median alone cannot judge the joint solution.  Evaluate the exact
    # existing residual (all range, root/orientation/temporal prior, and
    # foothold terms at their unchanged scales) at the three relevant states.
    range_projection_gate = bool(
        not projection_applied
        or projected_median <= prefit_median + 1e-10
    )
    projected_vector = np.r_[
        root, *(corrections[segment] for segment in active)
    ]
    prefit_full_residual = residual(x0)
    raw_full_residual = residual(optimized.x)
    projected_full_residual = residual(projected_vector)
    prefit_joint_objective = float(np.dot(
        prefit_full_residual, prefit_full_residual
    ))
    raw_joint_objective = float(np.dot(
        raw_full_residual, raw_full_residual
    ))
    projected_joint_objective = float(np.dot(
        projected_full_residual, projected_full_residual
    ))
    joint_objective_tolerance = 1e-10 * max(1.0, prefit_joint_objective)
    joint_projection_gate = bool(
        not projection_applied
        or projected_joint_objective
        <= prefit_joint_objective + joint_objective_tolerance
    )
    projection_acceptance_owner = (
        "FULL_EXISTING_RESIDUAL_WITH_POINT_CONSTRAINTS"
        if point_constraints else "RANGE_MEDIAN_WITHOUT_POINT_CONSTRAINTS"
    )
    projection_acceptance_gate = (
        joint_projection_gate if point_constraints else range_projection_gate
    )
    numerical_geometry_success = bool(
        optimized.success and np.isfinite(root).all() and rank == 3
        and math.isfinite(condition) and condition <= 1e8
        and max_correction <= config.maximum_segment_correction_rad * math.sqrt(3.0) + 1e-10
        and np.isfinite(innovation).all() and projection_inside
    )
    constraint_error = 0.0
    raw_constraint_error = 0.0
    prefit_constraint_error = 0.0
    prefit_constraint_terms = np.empty(0)
    raw_constraint_terms = np.empty(0)
    projected_constraint_terms = np.empty(0)
    foothold_projection_gate = True
    if point_constraints:
        prefit_points = corrected_proxy_points(
            base_rotations_world, previous, geometry
        )
        raw_points = corrected_proxy_points(
            base_rotations_world, raw_corrections, geometry
        )
        corrected_points = corrected_proxy_points(
            base_rotations_world, corrections, geometry
        )
        prefit_constraint_terms = np.concatenate([
            (root0 + prefit_points[name] - target)[list(constraint_axes)]
            for name, target in point_constraints.items()
        ])
        raw_constraint_terms = np.concatenate([
            (root + raw_points[name] - target)[list(constraint_axes)]
            for name, target in point_constraints.items()
        ])
        projected_constraint_terms = np.concatenate([
            (root + corrected_points[name] - target)[list(constraint_axes)]
            for name, target in point_constraints.items()
        ])
        prefit_constraint_error = max(
            float(np.linalg.norm(
                (root0 + prefit_points[name] - target)[list(constraint_axes)]
            ))
            for name, target in point_constraints.items()
        )
        raw_constraint_error = max(
            float(np.linalg.norm(
                (root + raw_points[name] - target)[list(constraint_axes)]
            ))
            for name, target in point_constraints.items()
        )
        constraint_error = max(
            float(np.linalg.norm(
                (root + corrected_points[name] - target)[list(constraint_axes)]
            ))
            for name, target in point_constraints.items()
        )
        foothold_projection_gate = bool(
            not projection_applied
            or (
                constraint_error <= prefit_constraint_error + 1e-10
                and constraint_error <= 4.0 * point_constraint_sigma_m
            )
        )
    success = bool(
        numerical_geometry_success
        and projection_acceptance_gate
        and foothold_projection_gate
    )
    projection_metrics = {
        **projection_metrics,
        "projection_applied": projection_applied,
        "prefit_range_median_abs_m": prefit_median,
        "raw_optimized_range_median_abs_m": raw_median,
        "projected_range_median_abs_m": projected_median,
        "projected_minus_raw_range_median_abs_m": projected_median - raw_median,
        "range_projection_gate": range_projection_gate,
        "projection_acceptance_owner": projection_acceptance_owner,
        "projection_acceptance_gate": projection_acceptance_gate,
        "prefit_full_residual_objective": prefit_joint_objective,
        "raw_optimized_full_residual_objective": raw_joint_objective,
        "projected_full_residual_objective": projected_joint_objective,
        "full_residual_objective_tolerance": joint_objective_tolerance,
        "joint_projection_gate": joint_projection_gate,
        "prefit_foothold_residual_m": prefit_constraint_error,
        "raw_optimized_foothold_residual_m": raw_constraint_error,
        "projected_foothold_residual_m": constraint_error,
        "projected_minus_raw_foothold_residual_m": (
            constraint_error - raw_constraint_error
        ),
        "foothold_projection_gate": foothold_projection_gate,
    }
    if not numerical_geometry_success:
        reason = "OPTIMIZER_OR_PROJECTED_GEOMETRY_FAILURE"
    elif not foothold_projection_gate:
        reason = "PROJECTED_FOOTHOLD_GATE_FAILURE"
    elif not projection_acceptance_gate:
        reason = (
            "PROJECTED_JOINT_OBJECTIVE_FAILURE"
            if point_constraints else "OPTIMIZER_OR_PROJECTED_GEOMETRY_FAILURE"
        )
    else:
        reason = "ACCEPTED"
    prefit_effective, _ = weights(prefit_innovation)
    raw_effective, _ = weights(raw_innovation)
    prefit_joint_data_objective = float(
        np.sum(prefit_effective * np.square(prefit_innovation / sigma))
        + np.sum(np.square(
            prefit_constraint_terms / point_constraint_sigma_m
        ))
    )
    raw_joint_data_objective = float(
        np.sum(raw_effective * np.square(raw_innovation / sigma))
        + np.sum(np.square(
            raw_constraint_terms / point_constraint_sigma_m
        ))
    )
    projected_joint_data_objective = float(
        np.sum(effective * np.square(innovation / sigma))
        + np.sum(np.square(
            projected_constraint_terms / point_constraint_sigma_m
        ))
    )
    projection_metrics = {
        **projection_metrics,
        "prefit_joint_data_objective": prefit_joint_data_objective,
        "raw_optimized_joint_data_objective": raw_joint_data_objective,
        "projected_joint_data_objective": projected_joint_data_objective,
        "projected_minus_prefit_joint_data_objective": (
            projected_joint_data_objective - prefit_joint_data_objective
        ),
    }
    return ArticulatedRangeResult(
        success,
        reason,
        root.copy(),
        {key: value.copy() for key, value in corrections.items()},
        {key: value.copy() for key, value in node_positions.items()},
        prefit_innovation.copy(), innovation.copy(), effective.copy(),
        facing_weight.copy(), covariance,
        rank, condition, int(optimized.nfev), float(optimized.cost), constraint_error,
        active, pose_rank, projection_metrics,
    )
