# prj.conf

# 基础功能
CONFIG_GPIO=y
CONFIG_SPI=y

# 日志功能
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# 如有需要串口打印
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# 如果您用到了多线程/多任务，可以启用
# CONFIG_THREAD_NAME=y

# 如果您需要低功耗、蓝牙等功能，再添加其他 Kconfig 配置
