#
# Copyright (c) 2026
# SPDX-License-Identifier: Apache-2.0
#

CONFIG_BT_LL_SOFTDEVICE_MULTIROLE=y
CONFIG_CHIP_MALLOC_SYS_HEAP_SIZE=10240
CONFIG_MPSL_WORK_STACK_SIZE=2048
CONFIG_SETTINGS_ZMS_SECTOR_COUNT=10
CONFIG_NVS=n
