#!/usr/bin/env python3
"""Audit static vertical-error consistency and layout-stretch coupling.

This script intentionally does not introduce a new solver or simulation.  It
only compares already-generated official tables and writes a tagged audit
bundle plus a LaTeX macro file for report numbers.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd


HEIGHT_ORDER = ["low", "mid", "high"]
PROD_VERSION = "v4-io"
PROD_EVAL_SET = "all8"
PROD_METHOD = "C_anchor_locked_OFFICIAL"


def repo_paths() -> dict[str, Path]:
    scripts_dir = Path(__file__).resolve().parent
    full_dir = scripts_dir.parent
    return {
        "full": full_dir,
        "tables": full_dir / "tables",
    }


def fmt1(value: float) -> str:
    return f"{value:.1f}"


def fmt2(value: float) -> str:
    return f"{value:.2f}"


def fmt3(value: float) -> str:
    return f"{value:.3f}"


def spearman(x: np.ndarray, y: np.ndarray) -> tuple[float, float]:
    try:
        from scipy import stats

        result = stats.spearmanr(x, y)
        return float(result.statistic), float(result.pvalue)
    except Exception:
        # Fallback gives the coefficient only; keep p-value explicit as NaN.
        rx = pd.Series(x).rank(method="average").to_numpy(dtype=float)
        ry = pd.Series(y).rank(method="average").to_numpy(dtype=float)
        rho = float(np.corrcoef(rx, ry)[0, 1])
        return rho, float("nan")


def write_macros(path: Path, values: dict[str, float]) -> None:
    lines = [
        "% Auto-generated by scripts/static_vertical_consistency_and_stretch.py",
        "% Do not hand-edit report numbers here.",
    ]
    for name in sorted(values):
        value = values[name]
        if name.endswith("Rtwo") or name.endswith("SlopeMmPerMm") or name.endswith("DopRho") or name.endswith("DopP"):
            formatted = fmt3(value)
        elif name == "TagDelayProxyMm":
            formatted = fmt3(value)
        elif name.endswith("ExpansionPercent"):
            formatted = fmt2(value)
        else:
            formatted = fmt1(value)
        lines.append(f"\\newcommand{{\\{name}}}{{{formatted}}}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    paths = repo_paths()
    default_out = paths["full"] / "vertical_consistency_stretch_20260613"
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", type=Path, default=default_out)
    args = parser.parse_args()
    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    official_path = paths["full"] / "audit_phase1d" / "tables" / "item1_item2_static_per_session.csv"
    dop_path = paths["tables"] / "revision2_dop_at_static_vicon_positions.csv"
    layout_path = paths["tables"] / "layout_abs_errors_all8.csv"
    surveyed_summary_path = paths["tables"] / "surveyed_anchor_baseline_summary.csv"
    raw_replay_summary_path = paths["tables"] / "tag_raw_replay_accuracy_summary.csv"
    common_mode_summary_path = paths["full"] / "audit_phase1c" / "tables" / "item2_common_mode_summary.csv"
    driver_summary_path = (
        paths["full"]
        / "vertical_driver_reconcile_20260613"
        / "tables"
        / "vertical_driver_reconcile_summary.csv"
    )

    official_all = pd.read_csv(official_path)
    official = official_all[official_all["case_id"] == "production_v4io_fixed_0mm"].copy()
    if len(official) != 24:
        raise RuntimeError(f"expected 24 official rows, found {len(official)}")

    dop = pd.read_csv(dop_path).copy()
    if len(dop) != 24:
        raise RuntimeError(f"expected 24 DOP rows, found {len(dop)}")

    layout_all = pd.read_csv(layout_path)
    layout = layout_all[
        (layout_all["version"] == PROD_VERSION) & (layout_all["eval_set"] == PROD_EVAL_SET)
    ].copy()
    if len(layout) != 8:
        raise RuntimeError(f"expected 8 v4-io layout rows, found {len(layout)}")

    surveyed_summary = pd.read_csv(surveyed_summary_path)
    surveyed_reestimated = surveyed_summary[
        (surveyed_summary["anchor_source"] == "OptiTrack truth anchors")
        & (surveyed_summary["delay_mode"] == "inter_anchor_delaycal")
        & (surveyed_summary["tag_method"] == "T4")
        & (surveyed_summary["eval_set"] == "all8")
    ]
    if len(surveyed_reestimated) != 1:
        raise RuntimeError(f"expected one surveyed re-estimated row, found {len(surveyed_reestimated)}")

    raw_replay_summary = pd.read_csv(raw_replay_summary_path)
    autopos_ablation = raw_replay_summary[
        (raw_replay_summary["version"] == PROD_VERSION)
        & (raw_replay_summary["tag_method"] == "T4")
        & (raw_replay_summary["eval_set"] == "all8")
    ]
    if len(autopos_ablation) != 1:
        raise RuntimeError(f"expected one AutoPos ablation row, found {len(autopos_ablation)}")

    common_mode_summary = pd.read_csv(common_mode_summary_path)
    common_mode = common_mode_summary[common_mode_summary["case"] == "v4io_common_mode"]
    if len(common_mode) != 1:
        raise RuntimeError(f"expected one common-mode row, found {len(common_mode)}")

    driver_summary = pd.read_csv(driver_summary_path)

    def driver_row(label: str) -> pd.Series:
        rows = driver_summary[driver_summary["label"] == label]
        if len(rows) != 1:
            raise RuntimeError(f"expected one driver row for {label}, found {len(rows)}")
        return rows.iloc[0]

    common0 = driver_row("common_mode_dtag0")
    vicon0 = driver_row("vicon_truth_reestimated_anchor_delays_dtag0")
    common91 = driver_row("common_mode_dtag91p153")
    vicon91 = driver_row("vicon_truth_reestimated_anchor_delays_dtag91.1532")

    official["official_abs_vertical_from_signed_mm"] = official["err_y_vertical_mm"].abs()
    by_height_rows = []
    check_rows = []
    macros: dict[str, float] = {}
    macros["DelayAblationSurveyedReestimatedRmseMm"] = float(
        surveyed_reestimated.iloc[0]["err_3d_rms_mm"]
    )
    macros["DelayAblationSelfCalibratedRmseMm"] = float(autopos_ablation.iloc[0]["err_3d_rms_mm"])
    macros["CommonModeNoTagDelayStaticMedianMm"] = float(common_mode.iloc[0]["static_t4_mean_median_mm"])
    macros["TagDelayProxyMm"] = float(common91["fixed_tag_delay_mm"])
    macros["CommonModeNoTagDelayVerticalMedianMm"] = float(common0["vertical_median_mm"])
    macros["CommonModeNoTagDelaySlopeMmPerM"] = float(common0["signed_vertical_slope_mm_per_m"])
    macros["ViconDelaycalNoTagDelayVerticalMedianMm"] = float(vicon0["vertical_median_mm"])
    macros["ViconDelaycalNoTagDelaySlopeMmPerM"] = float(vicon0["signed_vertical_slope_mm_per_m"])
    macros["CommonModeTagDelayProxyVerticalMedianMm"] = float(common91["vertical_median_mm"])
    macros["CommonModeTagDelayProxyThreeDMedianMm"] = float(common91["err_3d_median_mm"])
    macros["CommonModeTagDelayProxySlopeMmPerM"] = float(common91["signed_vertical_slope_mm_per_m"])
    macros["CommonModeTagDelayProxyRtwo"] = float(common91["signed_vertical_r2"])
    macros["ViconDelaycalTagDelayProxyVerticalMedianMm"] = float(vicon91["vertical_median_mm"])
    macros["ViconDelaycalTagDelayProxyThreeDMedianMm"] = float(vicon91["err_3d_median_mm"])
    macros["ViconDelaycalTagDelayProxySlopeMmPerM"] = float(vicon91["signed_vertical_slope_mm_per_m"])
    macros["ViconDelaycalTagDelayProxyRtwo"] = float(vicon91["signed_vertical_r2"])
    height_macro = {"low": "Low", "mid": "Mid", "high": "High"}
    for height in HEIGHT_ORDER:
        g = official[official["height"] == height].copy()
        gd = dop[dop["height"] == height].copy()
        signed_median = float(g["err_y_vertical_mm"].median())
        abs_median = float(g["official_abs_vertical_from_signed_mm"].median())
        table_abs_median = float(g["err_vertical_mm"].median())
        dop_abs_median = float(gd["err_vertical_mm"].median())
        ok = bool(abs_median + 1e-9 >= abs(signed_median))
        by_height_rows.append(
            {
                "height": height,
                "n_official": len(g),
                "official_signed_vertical_median_mm": signed_median,
                "official_abs_vertical_median_mm": abs_median,
                "official_err_vertical_column_median_mm": table_abs_median,
                "revision2_dop_abs_vertical_median_mm": dop_abs_median,
                "difference_official_abs_minus_dop_abs_mm": abs_median - dop_abs_median,
            }
        )
        check_rows.append(
            {
                "height": height,
                "median_abs_dz_mm": abs_median,
                "abs_median_signed_dz_mm": abs(signed_median),
                "passes_median_abs_ge_abs_median": ok,
            }
        )
        macro = height_macro[height]
        macros[f"Static{macro}OfficialSignedVerticalMedianMm"] = signed_median
        macros[f"Static{macro}OfficialAbsVerticalMedianMm"] = abs_median

    per_position = official[
        [
            "ID",
            "location",
            "height",
            "facing",
            "err_y_vertical_mm",
            "err_vertical_mm",
            "truth_y_vertical_mm",
            "aligned_y_vertical_mm",
        ]
    ].merge(
        dop[["ID", "err_vertical_mm", "vdop", "gdop", "hdop", "d3_std_mm"]],
        on="ID",
        how="left",
        suffixes=("_official", "_revision2_dop"),
    )
    per_position["official_abs_minus_revision2_dop_abs_mm"] = (
        per_position["err_vertical_mm_official"] - per_position["err_vertical_mm_revision2_dop"]
    )

    layout["vertical_residual_mm"] = layout["aligned_y_vertical_mm"] - layout["truth_y_vertical_mm"]
    lower = layout[layout["anchor"].isin(list("ABCD"))].copy()
    upper = layout[layout["anchor"].isin(list("EFGH"))].copy()
    lower_mean = float(lower["vertical_residual_mm"].mean())
    upper_mean = float(upper["vertical_residual_mm"].mean())
    stretch_mm = upper_mean - lower_mean
    truth_lower_mean = float(lower["truth_y_vertical_mm"].mean())
    truth_upper_mean = float(upper["truth_y_vertical_mm"].mean())
    aligned_lower_mean = float(lower["aligned_y_vertical_mm"].mean())
    aligned_upper_mean = float(upper["aligned_y_vertical_mm"].mean())
    truth_gap = truth_upper_mean - truth_lower_mean
    aligned_gap = aligned_upper_mean - aligned_lower_mean
    expansion_percent = 100.0 * stretch_mm / truth_gap
    truth_centroid = float(layout["truth_y_vertical_mm"].mean())
    aligned_centroid = float(layout["aligned_y_vertical_mm"].mean())
    centroid_residual = float(layout["vertical_residual_mm"].mean())

    macros["AnchorLowerVerticalResidualMeanMm"] = lower_mean
    macros["AnchorUpperVerticalResidualMeanMm"] = upper_mean
    macros["AnchorLayerVerticalResidualDifferenceMm"] = stretch_mm
    macros["AnchorTruthVerticalLayerGapMm"] = truth_gap
    macros["AnchorAlignedVerticalLayerGapMm"] = aligned_gap
    macros["AnchorVerticalExpansionPercent"] = expansion_percent
    macros["AnchorTruthVerticalCentroidMm"] = truth_centroid
    macros["AnchorAlignedVerticalCentroidMm"] = aligned_centroid
    macros["AnchorVerticalCentroidResidualMm"] = centroid_residual

    x = official["truth_y_vertical_mm"].to_numpy(dtype=float)
    y = official["err_y_vertical_mm"].to_numpy(dtype=float)
    slope, intercept = np.polyfit(x, y, 1)
    pred = slope * x + intercept
    residual = y - pred
    ss_res = float(np.sum(residual**2))
    ss_tot = float(np.sum((y - np.mean(y)) ** 2))
    r2 = 1.0 - ss_res / ss_tot
    pivot_x = float(np.mean(x))
    pivot_y = float(slope * pivot_x + intercept)
    official["vertical_fit_pred_mm"] = pred
    official["vertical_fit_residual_mm"] = residual

    reg_by_height_rows = []
    for height in HEIGHT_ORDER:
        g = official[official["height"] == height].copy()
        macro = height_macro[height]
        actual_signed_median = float(g["err_y_vertical_mm"].median())
        pred_median = float(g["vertical_fit_pred_mm"].median())
        residual_median = float(g["vertical_fit_residual_mm"].median())
        reg_by_height_rows.append(
            {
                "height": height,
                "n": len(g),
                "truth_y_median_mm": float(g["truth_y_vertical_mm"].median()),
                "signed_vertical_median_mm": actual_signed_median,
                "linear_fit_predicted_median_mm": pred_median,
                "median_residual_from_fit_mm": residual_median,
            }
        )
        macros[f"Tag{macro}SignedVerticalMedianMm"] = actual_signed_median
        macros[f"Tag{macro}VerticalFitPredictedMedianMm"] = pred_median
        macros[f"Tag{macro}VerticalFitResidualMedianMm"] = residual_median

    rho_vdop, p_vdop = spearman(
        per_position["vdop"].to_numpy(dtype=float),
        per_position["err_vertical_mm_official"].to_numpy(dtype=float),
    )
    macros["OfficialVerticalErrorVdopDopRho"] = rho_vdop
    macros["OfficialVerticalErrorVdopDopP"] = p_vdop
    macros["TagVerticalRegressionSlopeMmPerMm"] = float(slope)
    macros["TagVerticalRegressionSlopeMmPerM"] = float(slope * 1000.0)
    macros["TagVerticalRegressionInterceptMm"] = float(intercept)
    macros["TagVerticalRegressionPivotHeightMm"] = pivot_x
    macros["TagVerticalRegressionPivotErrorMm"] = pivot_y
    macros["TagVerticalRegressionRtwo"] = r2

    pd.DataFrame(by_height_rows).to_csv(out_dir / "tier_vertical_consistency.csv", index=False)
    pd.DataFrame(check_rows).to_csv(out_dir / "median_abs_signed_check.csv", index=False)
    per_position.to_csv(out_dir / "per_position_vertical_comparison.csv", index=False)
    layout[
        [
            "anchor",
            "truth_y_vertical_mm",
            "aligned_y_vertical_mm",
            "vertical_residual_mm",
            "err_3d_mm",
        ]
    ].to_csv(out_dir / "anchor_vertical_residuals.csv", index=False)
    pd.DataFrame(
        [
            {
                "lower_mean_vertical_residual_mm": lower_mean,
                "upper_mean_vertical_residual_mm": upper_mean,
                "upper_minus_lower_residual_mm": stretch_mm,
                "truth_lower_layer_mean_y_mm": truth_lower_mean,
                "truth_upper_layer_mean_y_mm": truth_upper_mean,
                "truth_layer_gap_mm": truth_gap,
                "aligned_lower_layer_mean_y_mm": aligned_lower_mean,
                "aligned_upper_layer_mean_y_mm": aligned_upper_mean,
                "aligned_layer_gap_mm": aligned_gap,
                "vertical_expansion_percent": expansion_percent,
                "truth_vertical_centroid_mm": truth_centroid,
                "aligned_vertical_centroid_mm": aligned_centroid,
                "centroid_vertical_residual_mm": centroid_residual,
            }
        ]
    ).to_csv(out_dir / "anchor_vertical_stretch_summary.csv", index=False)
    official[
        [
            "ID",
            "height",
            "facing",
            "truth_y_vertical_mm",
            "err_y_vertical_mm",
            "err_vertical_mm",
            "vertical_fit_pred_mm",
            "vertical_fit_residual_mm",
        ]
    ].to_csv(out_dir / "tag_vertical_regression_per_position.csv", index=False)
    pd.DataFrame(reg_by_height_rows).to_csv(out_dir / "tag_vertical_regression_by_height.csv", index=False)
    pd.DataFrame(
        [
            {
                "slope_mm_per_mm": float(slope),
                "slope_mm_per_m": float(slope * 1000.0),
                "intercept_mm": float(intercept),
                "pivot_height_mm": pivot_x,
                "pivot_error_mm": pivot_y,
                "r2": r2,
                "spearman_official_abs_vertical_vs_vdop_rho": rho_vdop,
                "spearman_official_abs_vertical_vs_vdop_p": p_vdop,
            }
        ]
    ).to_csv(out_dir / "tag_vertical_regression_summary.csv", index=False)
    write_macros(out_dir / "report_numbers.tex", macros)

    summary = {
        "inputs": {
            "official": str(official_path),
            "dop": str(dop_path),
            "layout": str(layout_path),
            "surveyed_summary": str(surveyed_summary_path),
            "raw_replay_summary": str(raw_replay_summary_path),
            "common_mode_summary": str(common_mode_summary_path),
            "driver_summary": str(driver_summary_path),
            "official_filter": {
                "case_id": "production_v4io_fixed_0mm",
            },
        },
        "outputs": str(out_dir),
        "tier_vertical_consistency": by_height_rows,
        "median_abs_signed_check": check_rows,
        "anchor_vertical_stretch": {
            "lower_mean_vertical_residual_mm": lower_mean,
            "upper_mean_vertical_residual_mm": upper_mean,
            "upper_minus_lower_residual_mm": stretch_mm,
            "truth_layer_gap_mm": truth_gap,
            "aligned_layer_gap_mm": aligned_gap,
            "vertical_expansion_percent": expansion_percent,
            "truth_vertical_centroid_mm": truth_centroid,
            "aligned_vertical_centroid_mm": aligned_centroid,
            "centroid_vertical_residual_mm": centroid_residual,
        },
        "tag_vertical_regression": {
            "slope_mm_per_mm": float(slope),
            "slope_mm_per_m": float(slope * 1000.0),
            "intercept_mm": float(intercept),
            "pivot_height_mm": pivot_x,
            "pivot_error_mm": pivot_y,
            "r2": r2,
            "by_height": reg_by_height_rows,
            "spearman_official_abs_vertical_vs_vdop_rho": rho_vdop,
            "spearman_official_abs_vertical_vs_vdop_p": p_vdop,
        },
        "foregrounded_calibration_numbers": {
            "delay_ablation_surveyed_reestimated_rmse_mm": macros[
                "DelayAblationSurveyedReestimatedRmseMm"
            ],
            "delay_ablation_self_calibrated_rmse_mm": macros["DelayAblationSelfCalibratedRmseMm"],
            "common_mode_no_tag_delay_static_median_mm": macros[
                "CommonModeNoTagDelayStaticMedianMm"
            ],
        },
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(f"wrote {out_dir}")
    print("\nTASK A consistency:")
    print(pd.DataFrame(by_height_rows).to_string(index=False, float_format=lambda v: f"{v:.3f}"))
    print("\nmedian(|dz|) >= |median(dz)| check:")
    print(pd.DataFrame(check_rows).to_string(index=False, float_format=lambda v: f"{v:.3f}"))
    print("\nTASK B anchor vertical stretch:")
    print(layout[["anchor", "vertical_residual_mm"]].to_string(index=False, float_format=lambda v: f"{v:.3f}"))
    print(
        f"lower_mean={lower_mean:.3f} mm, upper_mean={upper_mean:.3f} mm, "
        f"upper-lower={stretch_mm:.3f} mm, truth_gap={truth_gap:.3f} mm, "
        f"expansion={expansion_percent:.3f}%"
    )
    print(
        f"truth_centroid={truth_centroid:.3f} mm, aligned_centroid={aligned_centroid:.3f} mm, "
        f"centroid_residual={centroid_residual:.3f} mm"
    )
    print("\nTASK B tag vertical regression:")
    print(
        f"slope={slope:.6f} mm/mm ({slope * 1000.0:.1f} mm/m), "
        f"intercept={intercept:.3f} mm, pivot=({pivot_x:.3f} mm, {pivot_y:.3f} mm), R2={r2:.3f}"
    )
    print(pd.DataFrame(reg_by_height_rows).to_string(index=False, float_format=lambda v: f"{v:.3f}"))
    print(f"official abs vertical error vs VDOP Spearman rho={rho_vdop:.3f}, p={p_vdop:.3g}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
