CONFIG_I2C=y
CONFIG_I2C_NRFX=y            
CONFIG_I2C_INIT_PRIORITY=50  

CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_MAIN_STACK_SIZE=2048

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_PICOLIBC_IO_FLOAT=y          
CONFIG_LOG_BUFFER_SIZE=32768 
CONFIG_LOG_MODE_OVERFLOW=y
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=2
CONFIG_LOG_BACKEND_UART=n
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_RTT_MODE_DROP=n   
