# 通用打印/控制台
CONFIG_SERIAL=y
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_NEWLIB_LIBC=y

# GPIO & Pinctrl
CONFIG_PINCTRL=y
CONFIG_GPIO=y
CONFIG_GPIO_NRFX=y

# UART (用于 UWB)
CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_NRFX=y
CONFIG_RING_BUFFER=y

# I2C & 传感器 (MPU6050)
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_MPU6050=y
CONFIG_MPU6050_TRIGGER_OWN_THREAD=y

# ADC (用于 ECG)
CONFIG_ADC=y
CONFIG_ADC_NRFX_SAADC=y
CONFIG_ADC_ASYNC=y

# 支持 k_poll/k_poll_signal
CONFIG_POLL=y
CONFIG_HEAP_MEM_POOL_SIZE=16384

