#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -gt 1 ]; then
  echo "Usage: $0 [build_dir]" >&2
  exit 1
fi

build_dir="${1:-build-ref115-fast-6a}"

west build \
  -b decawave_dwm1001_dev/nrf52832 \
  -s apps/tag_usb \
  -d "$build_dir" \
  --no-sysbuild \
  --pristine=always \
  -- \
  -DAPP_TAG_ID=1 \
  -DAPP_TAG_BLE_ENABLE=0 \
  -DAPP_TAG_MCUBOOT_ENABLE=0 \
  -DAPP_TAG_USB_DIAG_TRACE=0 \
  -DAPP_TAG_TDMA_ENABLE=1 \
  -DAPP_TAG_TDMA_SLOT_INDEX=1 \
  -DAPP_TAG_TDMA_SLOT_COUNT=10 \
  -DAPP_TAG_TDMA_SLOT_PERIOD_MS=10 \
  -DAPP_TAG_TDMA_SLOT_ACTIVE_MS=9 \
  -DAPP_TAG_FIXED_MODE=0 \
  -DAPP_TAG_FAST_TRACKING=1 \
  -DAPP_TAG_FULL_SWEEP_INTERVAL=4 \
  -DAPP_TAG_MOTION_FULL_SWEEP_INTERVAL=4 \
  -DAPP_TAG_TRACK_ANCHOR_COUNT=6 \
  -DAPP_TAG_SUMMARY_PERIOD=1 \
  -DAPP_TAG_STATUS_PERIOD_MS=100 \
  -DAPP_TAG_PENDING_PRINT_PERIOD=1 \
  -DAPP_TAG_IMU_SAMPLE_PERIOD=2 \
  -DAPP_TAG_VERBOSE_RANGING=0 \
  -DAPP_TAG_VERBOSE_MEASUREMENTS=0 \
  -DAPP_TAG_LOC_MIN_QUALITY_PERCENT=0 \
  -DAPP_TAG_RANGE_CONTINUITY_ENABLE=0 \
  -DAPP_TAG_EKF_ENABLE=1 \
  -DAPP_TAG_EKF_MEAS_STD_MM=200 \
  -DAPP_TAG_EKF_RESIDUAL_GAIN_PCT=0 \
  -DAPP_TAG_EKF_PROC_ACCEL_MM_S2=1 \
  -DAPP_TAG_EKF_INIT_POS_STD_MM=200 \
  -DAPP_TAG_EKF_INIT_VEL_STD_MM_S=1000 \
  -DAPP_TAG_EKF_OUTLIER_GATE_MM=35 \
  -DAPP_TAG_RANGE_SOFT_RESIDUAL_MM=140 \
  -DAPP_TAG_RANGE_HARD_RESIDUAL_MM=260 \
  -DAPP_TAG_MOTION_EKF_MEAS_STD_MM=35 \
  -DAPP_TAG_MOTION_EKF_PROC_ACCEL_MM_S2=1800 \
  -DAPP_TAG_MOTION_EKF_OUTLIER_GATE_MM=220 \
  -DAPP_TAG_MOTION_SPEED_THRESHOLD_MM_S=100 \
  -DAPP_TAG_MOTION_IMU_DELTA_THRESHOLD_MG=250 \
  -DAPP_TAG_MOTION_IMU_GRAVITY_ERR_THRESHOLD_MG=140 \
  -DAPP_TAG_MOTION_RANGE_SOFT_BONUS_MM=140 \
  -DAPP_TAG_MOTION_RANGE_HARD_BONUS_MM=260

python3 scripts/write_build_source.py \
  --build-dir "$build_dir" \
  --source "scripts/build_ref115_fast.sh" \
  --command "$0 $*"

echo
echo "Built: $build_dir"
echo "Hex:   $build_dir/zephyr/zephyr.hex"
