#!/usr/bin/env bash
set -euo pipefail

if [ "${1:-}" != "" ] && [[ "${1}" =~ ^[0-9]+$ ]]; then
  TAG_ID="${TAG_ID:-$1}"
  TAG_BUILD_DIR="${2:-build-tag-ota-motion-tag${TAG_ID}}"
  MASTER_BUILD_DIR="${3:-build-master-ota-motion-tag${TAG_ID}}"
else
  TAG_BUILD_DIR="${1:-build-tag-ota-motion}"
  MASTER_BUILD_DIR="${2:-build-master-ota-motion}"
  TAG_ID="${TAG_ID:-0}"
fi
TAG_LOGICAL_ID="${TAG_LOGICAL_ID:-}"
if [ -z "$TAG_LOGICAL_ID" ]; then
  case "$TAG_ID" in
    115) TAG_LOGICAL_ID="1" ;;
    113) TAG_LOGICAL_ID="3" ;;
    127) TAG_LOGICAL_ID="2" ;;
    886) TAG_LOGICAL_ID="4" ;;
    *)
      if [[ "$TAG_ID" =~ ^[0-9]+$ ]] && [ "$TAG_ID" -lt 10 ]; then
        TAG_LOGICAL_ID="$TAG_ID"
      else
        TAG_LOGICAL_ID="0"
      fi
      ;;
  esac
fi
TAG_DEVICE_NAME="${TAG_DEVICE_NAME:-BS_AUTO}"
TAG_SIGN_VERSION="${TAG_SIGN_VERSION:-0.0.1+${TAG_ID}}"
TAG_SLOT_INDEX="${TAG_SLOT_INDEX:-0}"
TAG_SLOT_COUNT="${TAG_SLOT_COUNT:-10}"
MASTER_CMAKE_ARGS_DEFAULT="-DAPP_MASTER_OTA_TARGET_TOKEN_ID=${TAG_ID} -DAPP_MASTER_OTA_TARGET_NAME_PREFIX=BS"
export MASTER_CMAKE_ARGS="${MASTER_CMAKE_ARGS:-$MASTER_CMAKE_ARGS_DEFAULT}"

export TAG_SUMMARY_PERIOD="${TAG_SUMMARY_PERIOD:-1}"
export TAG_SIGN_VERSION
export TAG_CMAKE_ARGS="${TAG_CMAKE_ARGS:-\
-DAPP_TAG_ID=${TAG_LOGICAL_ID} \
-DAPP_TAG_BLE_TOKEN_ID=${TAG_ID} \
-DAPP_TAG_BLE_ENABLE=1 \
-DCONFIG_BT_DEVICE_NAME=\"${TAG_DEVICE_NAME}\" \
-DAPP_TAG_BLE_OTA_ENABLE=1 \
-DAPP_TAG_BLE_SETTINGS_ENABLE=0 \
-DAPP_TAG_BLE_COMPACT_STATUS=1 \
-DAPP_TAG_BLE_PACKET_BUNDLE_RECORDS=2 \
-DAPP_TAG_BLE_PACKET_BUNDLE_FLUSH_MS=250 \
-DAPP_TAG_MCUBOOT_ENABLE=1 \
-DAPP_TAG_MULTITAG_PLAN_MODE=1 \
-DAPP_TAG_ACTIVE_ANCHOR_0_ID=0 \
-DAPP_TAG_ACTIVE_ANCHOR_1_ID=1 \
-DAPP_TAG_ACTIVE_ANCHOR_2_ID=4 \
-DAPP_TAG_ACTIVE_ANCHOR_3_ID=5 \
-DAPP_TAG_STANDBY_ANCHOR_0_ID=2 \
-DAPP_TAG_STANDBY_ANCHOR_1_ID=6 \
-DAPP_TAG_RESERVE_ANCHOR_0_ID=3 \
-DAPP_TAG_RESERVE_ANCHOR_1_ID=7 \
-DAPP_TAG_EKF_ENABLE=1 \
-DAPP_TAG_EKF_MEAS_STD_MM=35 \
-DAPP_TAG_EKF_RESIDUAL_GAIN_PCT=0 \
-DAPP_TAG_EKF_PROC_ACCEL_MM_S2=500 \
-DAPP_TAG_EKF_INIT_POS_STD_MM=200 \
-DAPP_TAG_EKF_INIT_VEL_STD_MM_S=1200 \
-DAPP_TAG_EKF_OUTLIER_GATE_MM=120 \
-DAPP_TAG_FIXED_MODE=0 \
-DAPP_TAG_FIXED_ANCHOR_COUNT=4 \
-DAPP_TAG_FIXED_ANCHOR_0_ID=1 \
-DAPP_TAG_FIXED_ANCHOR_1_ID=2 \
-DAPP_TAG_FIXED_ANCHOR_2_ID=5 \
-DAPP_TAG_FIXED_ANCHOR_3_ID=6 \
-DAPP_TAG_FAST_TRACKING=1 \
-DAPP_TAG_FULL_SWEEP_INTERVAL=100 \
-DAPP_TAG_TRACK_ANCHOR_COUNT=6 \
-DAPP_TAG_TDMA_ENABLE=1 \
-DAPP_TAG_TDMA_SLOT_INDEX=${TAG_SLOT_INDEX} \
-DAPP_TAG_TDMA_SLOT_COUNT=${TAG_SLOT_COUNT} \
-DAPP_TAG_TDMA_SLOT_PERIOD_MS=25 \
-DAPP_TAG_TDMA_SLOT_ACTIVE_MS=20 \
-DAPP_TAG_PENDING_PRINT_PERIOD=1 \
-DAPP_TAG_IMU_SAMPLE_PERIOD=2 \
-DAPP_TAG_CONSOLE_SUMMARY_ENABLE=0 \
-DAPP_TAG_VERBOSE_RANGING=0 \
-DAPP_TAG_VERBOSE_MEASUREMENTS=0 \
-DAPP_TAG_VERBOSE_PERF=0 \
-DAPP_TAG_RANGE_CONTINUITY_ENABLE=1 \
-DAPP_TAG_USB_MIRROR_BLE_STATUS=0 \
-DAPP_TAG_LOC_MIN_QUALITY_PERCENT=20 \
-DAPP_TAG_RANGE_SOFT_RESIDUAL_MM=180 \
-DAPP_TAG_RANGE_HARD_RESIDUAL_MM=350 \
-DAPP_TAG_OUTPUT_MAX_RMS_MM=250 \
-DAPP_TAG_OUTPUT_MAX_MAX_MM=500 \
-DAPP_TAG_OUTPUT_MAX_STEP_MM=1200 \
-DAPP_TAG_MOTION_FULL_SWEEP_INTERVAL=8 \
-DAPP_TAG_MOTION_SPEED_THRESHOLD_MM_S=250 \
-DAPP_TAG_MOTION_RANGE_SOFT_BONUS_MM=140 \
-DAPP_TAG_MOTION_RANGE_HARD_BONUS_MM=260 \
-DAPP_TAG_MOTION_EKF_MEAS_STD_MM=35 \
-DAPP_TAG_MOTION_EKF_PROC_ACCEL_MM_S2=1800 \
-DAPP_TAG_MOTION_EKF_OUTLIER_GATE_MM=220 \
-DAPP_TAG_MOTION_IMU_DELTA_THRESHOLD_MG=250 \
-DAPP_TAG_MOTION_IMU_GRAVITY_ERR_THRESHOLD_MG=140}"

scripts/build_uwb_tag_ota_test.sh "$TAG_BUILD_DIR" "$MASTER_BUILD_DIR"
