#!/usr/bin/env python3
"""Generate the on-device firmware anchor layout (uwb_anchor_layout.{c,h}) from a
calibrated anchor_layout.json (V4-IO or V5).

Closes the "firmware layout is stale / has no per-anchor delays" gap from the
solver audit (REPORT.md sec 4c): the deployed `src/uwb_anchor_layout.c` carried a
different, delay-less, z-flipped geometry than the AutoPos calibration. This tool
regenerates it from the calibration JSON so a recalibration never needs hand
editing.

Three things it fixes vs the hand-written table:
  1. POSITIONS       -- copied from the JSON (V4-IO or V5).
  2. PER-ANCHOR DELAY-- a new `d_anchor_mm` field is added to the struct and each
                        row. For V5 the A-referenced DIFFERENTIAL is used
                        (differential_delay_mm) because the DW1000 hardware
                        TX/RX_ANT_DLY=16436 already applies the shared/common
                        antenna delay -- only the residual per-anchor difference
                        belongs on-device. (V4-IO's d_anchor_mm is already
                        A-referenced, so it is used directly.)
  3. Z-SIGN          -- AutoPos uses -z "up" for the high plane (z ~ -1568);
                        the firmware table used +z "up" (z ~ +1516). The default
                        flips z (negate) so the generated table matches firmware
                        convention. VERIFY against the physical mounting before
                        flashing (use --z-sign keep to disable).

Usage:
  python3 tools/generate_uwb_anchor_layout_c.py <anchor_layout.json> [-o OUTDIR]
          [--in-place] [--z-sign flip|keep] [--delay-field auto|d_anchor_mm|
          differential_delay_mm|none]

Default OUTDIR is tools/generated/ (safe -- does not touch the live src/). Pass
--in-place to write src/uwb_anchor_layout.c and include/uwb_anchor_layout.h.

NOTE: adopting the delay on-device also needs the GN cost function to add it
(`predicted = dist + d_anchor_mm`); this tool only regenerates the DATA table +
struct. See analysis/solver_v2_validation/REPORT.md for the firmware TODO.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ANCHOR_ORDER = "ABCDEFGH"


def _pick_delay_field(anchor: dict, mode: str) -> str | None:
    if mode == "none":
        return None
    if mode == "auto":
        # V5 layouts carry an A-referenced differential; prefer it. Fall back to
        # d_anchor_mm (V4-IO). auto -> None only if neither exists.
        if "differential_delay_mm" in anchor:
            return "differential_delay_mm"
        if "d_anchor_mm" in anchor:
            return "d_anchor_mm"
        return None
    return mode


def build_layout(layout: dict, z_sign: str, delay_field_mode: str):
    anchors = sorted(layout["anchors"], key=lambda a: a["id"])
    zmul = -1.0 if z_sign == "flip" else 1.0
    rows = []
    for a in anchors:
        aid = int(a["id"])
        label = a.get("label", ANCHOR_ORDER[aid] if aid < len(ANCHOR_ORDER) else "?")
        x = int(round(float(a["x_mm"])))
        y = int(round(float(a["y_mm"])))
        z = int(round(zmul * float(a["z_mm"])))
        fld = _pick_delay_field(a, delay_field_mode)
        d = int(round(float(a.get(fld, 0.0)))) if fld else 0
        rows.append((aid, label, x, y, z, d, fld))
    return rows


HEADER_H = """\
#ifndef UWB_ANCHOR_LAYOUT_H
#define UWB_ANCHOR_LAYOUT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

struct uwb_anchor_pose_mm {{
    uint8_t anchor_id;
    char label;
    int32_t x_mm;
    int32_t y_mm;
    int32_t z_mm;
    int32_t d_anchor_mm; /* per-anchor range delay correction (A-referenced, mm) */
}};

const struct uwb_anchor_pose_mm *uwb_anchor_layout_get(uint8_t anchor_id);
size_t uwb_anchor_layout_count(void);
bool uwb_anchor_layout_is_lower_plane(uint8_t anchor_id);
bool uwb_anchor_layout_is_upper_plane(uint8_t anchor_id);

#endif /* UWB_ANCHOR_LAYOUT_H */
"""


def render_c(rows, provenance: str) -> str:
    lines = [
        "/* AUTO-GENERATED by tools/generate_uwb_anchor_layout_c.py -- do not edit by hand.",
        f" * {provenance}",
        " */",
        '#include "uwb_anchor_layout.h"',
        "",
        '#include "uwb_ss_twr_shared.h"',
        "",
        "static const struct uwb_anchor_pose_mm uwb_anchor_layout[UWB_MAX_ANCHORS] = {",
    ]
    for (aid, label, x, y, z, d, fld) in rows:
        lines.append(f"    {{{aid}U, '{label}', {x}, {y}, {z}, {d}}},")
    lines += [
        "};",
        "",
        "const struct uwb_anchor_pose_mm *uwb_anchor_layout_get(uint8_t anchor_id)",
        "{",
        "    if (anchor_id >= UWB_MAX_ANCHORS) {",
        "        return NULL;",
        "    }",
        "",
        "    return &uwb_anchor_layout[anchor_id];",
        "}",
        "",
        "size_t uwb_anchor_layout_count(void)",
        "{",
        "    return UWB_MAX_ANCHORS;",
        "}",
        "",
        "bool uwb_anchor_layout_is_lower_plane(uint8_t anchor_id)",
        "{",
        "    return anchor_id < 4U;",
        "}",
        "",
        "bool uwb_anchor_layout_is_upper_plane(uint8_t anchor_id)",
        "{",
        "    return anchor_id >= 4U && anchor_id < UWB_MAX_ANCHORS;",
        "}",
        "",
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate firmware uwb_anchor_layout.{c,h}")
    ap.add_argument("layout_json", type=Path)
    ap.add_argument("-o", "--outdir", type=Path, default=REPO / "tools/generated")
    ap.add_argument("--in-place", action="store_true",
                    help="write src/uwb_anchor_layout.c + include/uwb_anchor_layout.h")
    ap.add_argument("--z-sign", choices=["flip", "keep"], default="flip",
                    help="flip (default): negate AutoPos z to firmware +z-up convention")
    ap.add_argument("--delay-field", default="auto",
                    choices=["auto", "d_anchor_mm", "differential_delay_mm", "none"])
    args = ap.parse_args(argv)

    layout = json.loads(args.layout_json.read_text(encoding="utf-8"))
    rows = build_layout(layout, args.z_sign, args.delay_field)
    used_field = next((r[6] for r in rows if r[6]), "none")
    solver = layout.get("solver") or layout.get("version") or "?"
    provenance = (f"source={args.layout_json}  solver={solver}  "
                  f"z_sign={args.z_sign}  delay_field={used_field}")

    c_text = render_c(rows, provenance)
    if args.in_place:
        c_path = REPO / "src/uwb_anchor_layout.c"
        h_path = REPO / "include/uwb_anchor_layout.h"
    else:
        args.outdir.mkdir(parents=True, exist_ok=True)
        c_path = args.outdir / "uwb_anchor_layout.c"
        h_path = args.outdir / "uwb_anchor_layout.h"
    h_path.write_text(HEADER_H.format(), encoding="utf-8")
    c_path.write_text(c_text, encoding="utf-8")

    print(f"[gen] {provenance}")
    print(f"[gen] wrote {c_path}")
    print(f"[gen] wrote {h_path}")
    print("[gen] anchor table (firmware convention):")
    for (aid, label, x, y, z, d, fld) in rows:
        print(f"    {label}: x={x:6d} y={y:6d} z={z:6d}  d_anchor_mm={d:+4d}")
    if not args.in_place:
        print("[gen] (safe mode: wrote to tools/generated/. Use --in-place to update src/.)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
